openc3-cmd-tlm-api/app/channels/config_events_channel.rb
openc3-cmd-tlm-api/app/controllers/plugins_controller.rb
openc3-cmd-tlm-api/app/controllers/process_status_controller.rb
openc3-cmd-tlm-api/app/models/config_events_api.rb
openc3-init/plugins/packages/openc3-tool-admin/src/tools/OpenC3Admin/tabs/PluginsTab.vue
openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue
openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsEvents.vue
openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsMonitor.vue
openc3/bin/openc3cli
openc3/lib/openc3/microservices/decom_microservice.rb
openc3/lib/openc3/models/model.rb
openc3/lib/openc3/models/plugin_model.rb
openc3/lib/openc3/models/target_model.rb
openc3/lib/openc3/operators/operator.rb
openc3/lib/openc3/topics/limits_event_topic.rb
openc3/spec/models/target_model_spec.rb
openc3/spec/topics/limits_event_topic_spec.rb
playwright/storageState.json
playwright/tests/limits-monitor.spec.ts

Better cleanup and handle limits

---

openc3-init/plugins/packages/openc3-demo/targets/INST/lib/sim_inst.rb
openc3/lib/openc3/interfaces/simulated_target_interface.rb
openc3/lib/openc3/utilities/simulated_target.rb

Greatly improves CPU utilization used by INST sim targets.  
Reduces runs from 100Hz to 10Hz
Removes IO of reading Position/Attitude Files

Optimize Simulated Target for INST

---

compose.yaml

Fixes Rootless podman for versions 5.0.5+ (and probably any linux with SELinux)

Support Selinux

---

openc3-cmd-tlm-api/app/controllers/script_autocomplete_controller.rb
openc3-init/plugins/packages/openc3-tool-tlmviewer/package.json
openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/EditScreenDialog.vue
openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/Openc3Screen.vue
openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/TlmViewer.vue
openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/autocomplete/index.js
openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/autocomplete/screenCompleter.js

Screen autocomplete

---

openc3-init/plugins/packages/openc3-tool-common/src/components/LogMessages.vue
openc3/data/config/_id_items.yaml
openc3/data/config/_id_params.yaml
openc3/data/config/_items.yaml
openc3/data/config/_params.yaml

Add severity level filter to log messages

---

openc3-cmd-tlm-api/app/controllers/api_controller.rb
openc3/lib/openc3/utilities/authentication.rb

Refresh tokens 60 seconds before expire

---

openc3-script-runner-api/app/models/running_script.rb

Add newlines to script runner logs

---

openc3-init/plugins/packages/openc3-tool-common/src/services/openc3-api.js
openc3/lib/openc3/api/interface_api.rb
openc3/lib/openc3/microservices/interface_microservice.rb
openc3/lib/openc3/topics/interface_topic.rb
openc3/spec/microservices/interface_microservice_spec.rb

Add params to connect_interface

---

openc3-cmd-tlm-api/app/controllers/api_controller.rb
openc3-cmd-tlm-api/config.ru
openc3-cmd-tlm-api/config/application.rb
openc3-script-runner-api/config.ru
openc3-script-runner-api/config/application.rb
openc3/lib/openc3/microservices/decom_microservice.rb
openc3/lib/openc3/microservices/interface_microservice.rb
openc3/lib/openc3/microservices/microservice.rb
openc3/lib/openc3/topics/command_topic.rb
openc3/lib/openc3/topics/telemetry_decom_topic.rb
openc3/lib/openc3/utilities/open_telemetry.rb
openc3/openc3.gemspec

closes #171 
To test add to compose.yaml:
```
openc3-jaeger:
image: "${OPENC3_REGISTRY}/jaegertracing/all-in-one:1.38"
command: ["--memory.max-traces=1000000"]
ports:
- "127.0.0.1:16686:16686"
restart: on-failure
environment:
- "COLLECTOR_OTLP_ENABLED=true"
env_file:
- ".env"
```
Add to .env:
```
OTEL_EXPORTER_OTLP_ENDPOINT=http://openc3-jaeger:4318
OPENC3_OTEL=CMD__TLM__API
```

Implement OpenTelemetry tracing

---

openc3.sh
openc3/bin/openc3cli
openc3/data/config/target.yaml

Fix xtce_converter

---

openc3-init/plugins/packages/openc3-tool-common/src/tools/base/components/Notifications.vue

Indicate max notifications reached

---

openc3/lib/openc3/script/api_shared.rb
openc3/spec/script/api_shared_spec.rb

Fix for packets not received

---

openc3.code-workspace
openc3/lib/openc3/models/cvt_model.rb
openc3/lib/openc3/packets/packet.rb
openc3/spec/models/cvt_model_spec.rb
openc3/spec/packets/packet_spec.rb

Fix packet decom of array data

---

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/services/openc3-api.js
openc3/lib/openc3/api/tlm_api.rb

Add inject_tlm to javascript api

---

openc3/lib/openc3/models/target_model.rb
openc3/spec/models/target_model_spec.rb

break out reducer microservice by default

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/microservices/EXAMPLE/example_target.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/microservices/TEMPLATED/scpi_target.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/plugin.txt

Update demo microservices to inherit Microservice

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/EditScreenDialog.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/Widget.js

Default various SETTINGS to px

---

openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb
openc3/lib/openc3/utilities/aws_bucket.rb

#496 Add an optional flag to `list_files`  to return metadata for an object.

Add optional flag to return object metadata

---

openc3-cosmos-cmd-tlm-api/app/models/streaming_api.rb
openc3-cosmos-cmd-tlm-api/app/models/streaming_object.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/SettingsDialog.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/TlmGrapher.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue

Removed immediate redraws on every data change.  Add alive? check to handoff in streaming api.
Fixed changing items causing TlmGrapher to crash.

TlmGrapher improvements

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
openc3-cosmos-script-runner-api/app/controllers/scripts_controller.rb
openc3-cosmos-script-runner-api/app/models/running_script.rb

Add new test suite option

---

openc3.bat
openc3.sh

Add docker network to scripts

---

openc3/lib/openc3/models/plugin_model.rb
openc3/lib/openc3/utilities/ruby_lex_utils.rb
openc3/spec/utilities/ruby_lex_utils_spec.rb

Improve instrumentation

---

openc3-cosmos-script-runner-api/app/models/running_script.rb
openc3/lib/openc3/script/script_runner.rb

Fix run_script

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tablemanager/src/tools/TableManager/TableItem.vue

Use VWidget to format TableItem

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/StatusTab.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsMonitor.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/LabelvaluelimitsbarWidget.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/ValuelimitsbarWidget.vue

Move limits set to LimitsMonitor and fix limitsbar

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/package.json
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/package.json
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/EditScreenDialog.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/EditDialog.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/InterfacesTab.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/MicroservicesTab.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/RedisTab.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/RoutersTab.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/TargetsTab.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/ToolsTab.vue
openc3-cosmos-init/plugins/yarn.lock

Ace edit json dialog and redis

---

openc3/lib/openc3/logs/packet_log_reader.rb
openc3/lib/openc3/logs/packet_log_writer.rb
openc3/spec/logs/packet_log_writer_spec.rb

target_index was incorrectly incrementing with each new log file created by the same PacketLogWriter rendering it invalid.

fix target_index in packet log writer

---

openc3/bin/openc3cli

Improve COSMOS 4 migration

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/TlmGrapher.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/LinegraphWidget.vue

Pause graph when clicking

---

openc3-cosmos-cmd-tlm-api/app/controllers/tables_controller.rb
openc3-cosmos-cmd-tlm-api/app/models/table.rb
openc3-cosmos-cmd-tlm-api/spec/models/table_spec.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tablemanager/src/tools/TableManager/TableManager.vue
openc3/lib/openc3/tools/table_manager/table_manager_core.rb
openc3/spec/tools/table_manager/table_manager_core_spec.rb

Table lookup matching definitions and then ask user

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/procedures/target_file.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
openc3-cosmos-script-runner-api/app/models/running_script.rb
openc3/lib/openc3/script/storage.rb
openc3/lib/openc3/utilities/store_autoload.rb

Add download_file API

---

openc3/lib/openc3/models/target_model.rb
openc3/lib/openc3/utilities/process_manager.rb

Warn on screen ERB error

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-handbooks/src/tools/Handbooks/Item.vue

Add ID Value to handbook output

---

openc3-cosmos-init/Dockerfile
openc3/lib/openc3/api/limits_api.rb
openc3/lib/openc3/api/tlm_api.rb
openc3/lib/openc3/models/cvt_model.rb
openc3/spec/api/limits_api_spec.rb
openc3/spec/api/tlm_api_spec.rb
scripts/release/package_audit_lib.rb

Allow LATEST in get_limits

---

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue

Fix TlmGrapher end time

---

openc3-cosmos-init/init.sh
openc3/Rakefile

This is a small commit to fix some issues that were encountered when running Cosmos locally.
* Fixes included:
* The new updates to `minio/mc` have caused a different behavior when applying the policy so that it will fail if the specified policy is already in effect. The small patch just allows it to fail and move on.
* I have made the `:build` task a prerequisite to the `:gems` tasks. Without the `:build` task the generated gem doesn't include all the necessary library files that are generated by `make`. If you set `OPENC3_DEVEL` or `OPENC3_PATH` to `/openc3` in the Dockerfile for both the `openc3-cosmos-cmd-tlm-api` and the `openc3-cosmos-script-runner-api` it will throw errors about not being able to find these library files.

Small Patches to Help with the Local Workflow

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/procedures/checks.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/screens/commanding.txt

Show ENV usage in screen

---

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/DetailsDialog.vue

Display raw UINT/INT values as hex

---

openc3/lib/openc3/config/config_parser.rb
openc3/lib/openc3/config/meta_config_parser.rb
openc3/lib/openc3/core_ext/string.rb
openc3/lib/openc3/models/microservice_model.rb
openc3/lib/openc3/models/target_model.rb
openc3/lib/openc3/models/tool_model.rb
openc3/lib/openc3/models/widget_model.rb
openc3/lib/openc3/utilities/cli_generator.rb
openc3/spec/config/config_parser_spec.rb
openc3/spec/core_ext/string_spec.rb

Comment out ERB

---

openc3/lib/openc3/io/json_rpc.rb
openc3/spec/packets/packet_spec.rb

Hash as_json handle unlimited items

---

docs.openc3.com/docs/configuration/protocols.md
docs.openc3.com/docs/getting-started/gettingstarted.md
docs.openc3.com/docs/getting-started/installation.md
docs.openc3.com/docs/getting-started/key_concepts.md
docs.openc3.com/docs/getting-started/podman.md
docs.openc3.com/docs/getting-started/requirements.md
docs.openc3.com/docs/guides/cfs.md

I'll need to regenerate the site before merge but check this out and let me know what you think. This is the result of a few recent discussions we've had about confusion about the architecture and things we're doing.
closes #816

Add Key Concepts page

---

openc3.sh

If building and running with `build-ubi` and `start-ubi` the images are subject to the `OPENC3_IMAGE_SUFFIX`. This adds the suffix to the `cli` and `cliroot` calls that will point it to the correct image.

Add OPENC3_IMAGE_SUFFIX to the cli and cliroot Calls

---

openc3/lib/openc3/accessors/accessor.rb
openc3/lib/openc3/accessors/json_accessor.rb
openc3/python/openc3/accessors/accessor.py
openc3/python/openc3/accessors/json_accessor.py
openc3/python/test/accessors/test_cbor_accessor.py
openc3/python/test/accessors/test_html_accessor.py
openc3/python/test/accessors/test_json_accessor.py
openc3/python/test/accessors/test_xml_accessor.py
openc3/spec/accessors/cbor_accessor_spec.rb
openc3/spec/accessors/html_accessor_spec.rb
openc3/spec/accessors/json_accessor_spec.rb
openc3/spec/accessors/xml_accessor_spec.rb

Make json, cbor, xml, html enforce data types

---

openc3/lib/openc3/microservices/decom_microservice.rb
openc3/lib/openc3/packets/packet.rb
openc3/python/openc3/microservices/decom_microservice.py
openc3/python/openc3/packets/packet.py
openc3/spec/packets/parsers/processor_parser_spec.rb

Only run processors in decom microservice

---

openc3/lib/openc3/interfaces/tcpip_client_interface.rb
openc3/lib/openc3/interfaces/tcpip_server_interface.rb
openc3/lib/openc3/streams/tcpip_socket_stream.rb

Add TCPIP keepalive options

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-ace-diff/src/diff-match-patch.js
openc3-cosmos-init/plugins/packages/openc3-cosmos-ace-diff/src/index.js
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/PluginDialog.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PluginsTab.vue

Add warning about unmerged diffs and fix diff logic

---

openc3/python/openc3/streams/tcpip_client_stream.py

Tested by opening local TCPIP server port in irb and observing connection
```
require 'socket'
socket = TCPServer.new(4242)
client = socket.accept
```
closes #1033

Fix python tpcip client connection

---

openc3/lib/openc3/interfaces/interface.rb
openc3/lib/openc3/microservices/interface_microservice.rb
openc3/python/openc3/interfaces/interface.py
openc3/python/openc3/microservices/interface_microservice.py

Make periodic command ensure connected before sending

Ensure disconnect called at least once on interface. 

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/tables/procedures/download.py
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/tables/procedures/upload.py
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tablemanager/src/tools/TableManager/TableManager.vue
openc3/python/openc3/script/storage.py

Allow python upload/download in TableManager

---

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/icons/index.js

Since we're using the rux-status web component we must map to known astro status values.
closes #1014

Map fatal to critical

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/FileOpenSaveDialog.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/services/axios.js

This handles a file being deleted out from under you silently rather than popping a 404 error. I'm also cleaning up the recently used which I wasn't even handling before. If you access the file from the recently used it still pops up a warning but then removes the file from the recents.

Handle 404 errors in Script Runner

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue

Definitely a bug when you run a script and then try to click the drop down and choose another file. This causes the editor to detect a change and the filename gets changed to the original with a *. At that point if you run or click save you will overwrite. But the process is pretty manual in that you have to select a file from that drop down.
I kind of liked the ability to see the files that we drilled into during the test but I couldn't figure out a way to disable the change callback during this change.

Clear SR file cache when stopped

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/CmdTlmServer.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/services/openc3-api.js
openc3/lib/openc3/interfaces/interface.rb
openc3/lib/openc3/microservices/interface_microservice.rb
openc3/python/openc3/interfaces/interface.py
openc3/python/test/interfaces/test_interface.py
openc3/spec/interfaces/interface_spec.rb
openc3/templates/tool_svelte/src/services/openc3-api.js

CmdTlmServer clear counters

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/ResultsDialog.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/RunningScripts.vue
openc3-cosmos-script-runner-api/app/models/running_script.rb
openc3-cosmos-script-runner-api/app/models/script.rb
openc3-cosmos-script-runner-api/scripts/running_script.py
openc3/lib/openc3/script/suite_results.rb
openc3/python/openc3/script/suite_results.py

Add suite, group, script to report file name

---

openc3/lib/openc3/models/plugin_model.rb
openc3/lib/openc3/models/python_package_model.rb
openc3/python/openc3/io/stderr.py
openc3/python/openc3/io/stdout.py

Fix import of pandas, and use of PYPI_URL

---

openc3/lib/openc3/packets/json_packet.rb
openc3/spec/install/config/targets/INST/cmd_tlm/inst_tlm.txt
openc3/spec/packets/json_packet_spec.rb

#933 added support for graphing telemetry items. This relied on syntax which used brackets '[]' to determine that an array item was requested. This broke normal items with brackets from working, e.g. 'MYTLM[1]'.

Support item names with brackets

---

openc3/lib/openc3/models/gem_model.rb
openc3/lib/openc3/utilities/process_manager.rb

Handle upgrade with multiple installed same plugins

---

openc3/python/openc3/models/model.py
openc3/python/test/models/test_model.py

https://docs.python.org/3/library/typing.html

Start add typing to python lib

---

openc3-cosmos-cmd-tlm-api/app/controllers/application_controller.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/RunningScripts.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/AppFooter.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/components/UserMenu.vue
openc3-cosmos-script-runner-api/app/controllers/application_controller.rb
openc3-cosmos-script-runner-api/app/controllers/scripts_controller.rb
openc3-cosmos-script-runner-api/app/models/completed_script.rb
openc3-cosmos-script-runner-api/app/models/running_script.rb
openc3-cosmos-script-runner-api/app/models/script.rb
openc3-cosmos-script-runner-api/scripts/running_script.py

Add username to Execution status

---

openc3/openc3.gemspec

Bump redis-client version

---

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/Widget.js

Desired effect is disabling max param check if max_params is null.
Current logic also disables max param check if max_params (and min params) are set to 0.
I hit this in a custom widget that didn't need any parameters.

prevent 0 max params registering as no-maximum

---

.github/workflows/python_unit_tests.yml
docs.openc3.com/docs/guides/raspberrypi.md
openc3/lib/openc3/api/tlm_api.rb
openc3/lib/openc3/packets/packet_config.rb
openc3/python/openc3/api/tlm_api.py
openc3/python/openc3/interfaces/tcpip_server_interface.py
openc3/python/openc3/packets/packet_config.py
openc3/python/openc3/packets/packet_item.py
openc3/python/test/api/test_cmd_api.py
openc3/python/test/api/test_tlm_api.py
openc3/python/test/packets/test_packet_config.py
openc3/spec/api/tlm_api_spec.rb
openc3/spec/packets/packet_config_spec.rb

Fixed Python GENERIC_READ_CONVERSION, GENERIC_WRITE_CONVERSION, HAZARDOUS without descriptions, SEG_POLY_READ_CONVERSION, SEG_POLY_WRITE_CONVERSION, MINIMUM_VALUE, MAXIMUM_VALUE, DEFAULT_VALUE.
Removed Python TEMPLATE, TEMPLATE_FILE (new Python code should use RESPONSE and ERROR_RESPONSE)

Fix several python packet config options

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue

Fix Script execute selection and run from here

---

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/SettingsTab.vue
openc3/bin/pipinstall
openc3/lib/openc3/models/gem_model.rb
openc3/lib/openc3/models/plugin_model.rb
openc3/lib/openc3/models/python_package_model.rb
openc3/lib/openc3/models/scope_model.rb

Fix pypi url usage

---

openc3/Rakefile
openc3/ext/openc3/ext/burst_protocol/burst_protocol.c
openc3/ext/openc3/ext/burst_protocol/extconf.rb
openc3/lib/openc3/interfaces/protocols/burst_protocol.rb
openc3/openc3.gemspec
openc3/spec/interfaces/protocols/burst_protocol_spec.rb
openc3/test/benchmarks/burst_protocol_benchmark.rb

Speed improvements are unfortunately pretty small in the benchmarking I did.  0-5%

burst protocol c extension

---

openc3/python/openc3/packets/limits_response.py
openc3/python/test/api/test_limits_api.py
openc3/python/test/packets/test_packet_config.py
openc3/templates/conversion/conversion.py
openc3/templates/limits_response/response.py

Python conversion generator returns value

---

openc3/python/openc3/utilities/logger.py
openc3/python/test/utilities/test_logger.py

Fix python log time

---

docs.openc3.com/docs/guides/script-writing.md
docs.openc3.com/docs/tools/script-runner.md
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/SuiteRunner.vue
openc3-cosmos-script-runner-api/scripts/running_script.py
openc3/python/openc3/script/suite_runner.py

Add popups for Suite Runner checkboxes

---

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/EditScreenDialog.vue

Right click screen keyword for docs

---

openc3-cosmos-cmd-tlm-api/app/controllers/model_controller.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue

ScriptRunner was attaching the keydown event to window rather than the current editor.  This causes a new hook to be attached everytime a user leaves scriptrunner and came back.  Old hooks remained bound to old editors, so a ctrl-s would cause multiple saves with a random last save being the winner and ending up being committed.
Fix is to attach to the editor, not window.

Prevent ScriptRunner Ctrl-S Save from Saving Old Buffers

---

openc3-cosmos-init/Dockerfile

We recently encountered this error when running with buildkit on docker version is 27.0.1, through WSL2. More recent docker versions seem to be failing builds based on Dockerfile best-practice checks. This was a `./openc3.sh build-ubi` build- not docker compose.
https://docs.docker.com/reference/build-checks/from-as-casing/

fix "FromAsCasing" buildkit check

---

openc3-cosmos-cmd-tlm-api/app/controllers/microservices_controller.rb

Will allow pointing to the correct service for a normal operator in Kubernetes

Add environment variable for dynamic operator hostname

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-bucketexplorer/src/tools/BucketExplorer/BucketExplorer.vue

Bucket Explorer list latest first

---

openc3/python/openc3/microservices/interface_microservice.py
openc3/python/test/microservices/test_interface_microservice.py

Remove extra connect in python_microservice

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/cmd_tlm/inst_tlm.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/lib/sim_inst.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/screens/array.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/cmd_tlm/inst_tlm.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/lib/sim_inst.py
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/screens/array.txt
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/GraphWidget.js
playwright/tests/data-extractor.spec.ts

Allow array index on graph widget

---

openc3/lib/openc3/utilities/authentication.rb
openc3/python/examples/cosmos_web_socket_example.py
openc3/python/openc3/script/web_socket_api.py

closes #1417 
This is a bit of a hack because the "right way" as described here: https://websockets.readthedocs.io/en/stable/topics/authentication.html#machine-to-machine-authentication doesn't seem to work. I get alternating results of `RuntimeError: Unauthorized` followed by `websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)`.

Fix python web socket in Enterprise

---

openc3/lib/openc3/microservices/timeline_microservice.rb
openc3/python/openc3/script/stream.py
openc3/spec/microservices/timeline_microservice_spec.rb
openc3/spec/models/activity_model_spec.rb

This is in support of the ability to disable calendar execution

Calendar settings

---

docs.openc3.com/docs/getting-started/installation.md

Somewhat amusingly, the documentation's note regarding reporting an issue was broken, thus making it impossible to report the issue itself. For convenience, here is the live page which has the bad link: https://docs.openc3.com/docs/getting-started/installation
The link syntax was broken and was generating a bad URL with a `">` included, which leads to a GitHub 404 page. I've removed the extra parts, and I believe the link now works as-expected, giving the option of which type of New Issue to create (although it may be nice if the issue types included "Documentation changes" or similar).
Additionally, this was the only `:::note` block which was tabbed-in across all the docs, so I made the choice to un-tab that. Not sure if that was meant to be tabbed in but my guess is that it should match …

Fix markdown issue in documentation issue reporting note

---

.env
.github/workflows/cli.yml
openc3/bin/openc3cli
openc3/lib/openc3/utilities/cli_generator.rb
playwright/playwright.sh

There is no longer a default language for the generators.
If OPENC3_LANGUAGE is not set, the final argument to _bundle exec ruby bin/openc3cli generate_ must be **--ruby** or -**-python**.
If OPENC3_LANGUAGE is set, it must be exactly **ruby** or **python**.
If OPENC3_LANGUAGE is set, the final argument can be (missing or) anything other than **--ruby** or **--python**, then OPENC3_LANGUAGE will be used.
If both are set but only one is correct, the correct one will be used.
If neither are set or both are incorrect the script will abort with a descriptive message.
NOTE: the command line arguments must have the leading dashes, but the ENV var must not.

Generator requires language

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-bucketexplorer/src/tools/BucketExplorer/BucketExplorer.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
playwright/tests/data-viewer.spec.ts

Fix fileDialogCallback promise logic

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/VWidget.js
openc3-cosmos-script-runner-api/app/models/running_script.rb
openc3-cosmos-script-runner-api/scripts/running_script.py
openc3/lib/openc3/script/api_shared.rb
openc3/python/openc3/script/api_shared.py

SR line delay menu option and log line delay changes

---

openc3/lib/openc3/io/json_api.rb

This basically copies the same structure as what is in `microservices_controller.rb` and allowing the operator hostname to be set through the `OPENC3_OPERATOR_HOSTNAME` environment variable.

Applied OPENC3_OPERATOR_HOSTNAME to json_api.rb

---

openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/FileDialog.vue

Allow upload and delete to /tmp

---

openc3/ext/openc3/ext/structure/structure.c
openc3/lib/openc3/packets/packet.rb
openc3/lib/openc3/packets/structure.rb
openc3/lib/openc3/packets/structure_item.rb
openc3/spec/accessors/binary_accessor_spec.rb
openc3/spec/packets/packet_config_spec.rb
openc3/spec/packets/structure_item_spec.rb

Fixes issues with mixed types of variable bit size items, and resolves ambiguity based on item create order.

Deterministic recalculate bit offsets

---

openc3/python/openc3/interfaces/tcpip_server_interface.py
openc3/python/test/interfaces/test_tcpip_server_interface.py

closes #1572 
I created an interface in the demo by doing:
```
INTERFACE TCPIP_INT openc3/interfaces/tcpip_server_interface.py 52001 52001 10.0 None
MAP_TARGET EXAMPLE
```
And then exposed port 52001 in the compose.yaml. I was able to talk to it via `nc localhost 52001` and see the client number increase and the text show up in `UNKNOWN`.
Ideally we would have a better test case for this like converting the TEMPLATED target to python. However that port looks a little bit involved because of the use of `InterfaceThread` from `tools/cmd_tlm_server/interface_thread.rb` which currently has no Python equivalent.

Fix python tcpip_server_interface

---

playwright/tests/bucket-explorer.spec.ts

needed to upload to a path that 'Operator' had permissions for

Fix Bucket Explorer auto-refresh playwright test for enterprise

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-packetviewer/src/tools/PacketViewer/PacketViewer.vue

Add key to PacketViewer table

---

openc3/lib/openc3/models/cvt_model.rb
openc3/spec/models/cvt_model_spec.rb

closes #1606 
Didn't expect this to be a backend change but it was returning a single [nil] for an item that exists but hasn't been populated which is inconsistent with all the other items which return a [value, limits_state].

CvtModel get_tlm_values return consistent results

---

openc3/lib/openc3/api/limits_api.rb
openc3/lib/openc3/packets/packet_item.rb
openc3/spec/api/limits_api_spec.rb
openc3/spec/packets/packet_item_spec.rb

closes #1596 
Yet another backend change for the frontend bug. I can't understand why we were deleting the 'enabled' attribute instead of setting it to false but that seems wrong and it breaks the frontend because if the only field is 'enabled' now I have no limits at all. Note that the Python code in packet_item.py is already setting enabled = False correctly.

Disabling limits sets enabled to false

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptLogMessages.vue
openc3-cosmos-script-runner-api/app/models/running_script.rb
openc3-cosmos-script-runner-api/scripts/running_script.py

Colorize SR output on CHECK success/failure

---

openc3/python/openc3/api/target_api.py

closes #1410 
Ruby API already had `get_target_names` with `system` permission

Change get_target_names permission to 'system'

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue

Hide start button when Suite Runner active

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/RunningScripts.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
openc3-cosmos-script-runner-api/app/models/completed_script.rb
openc3-cosmos-script-runner-api/app/models/running_script.rb
openc3-cosmos-script-runner-api/scripts/running_script.py

Fix ScriptRunner Execute text when file modified

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataextractor/src/tools/DataExtractor/DataExtractor.vue

Format binary output as hex

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/screens/rollup.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/screens/rollup.txt
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Openc3Screen.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/CanvasimageWidget.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/CanvasimagevalueWidget.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/RollupWidget.vue

Default screen cursor, pointer only on linked screens

---

openc3/lib/openc3/packets/packet_config.rb
openc3/lib/openc3/utilities/store_queued.rb
openc3/python/openc3/config/config_parser.py
openc3/python/openc3/packets/packet.py
openc3/python/openc3/packets/packet_config.py

Adds a helpful method to create a PacketConfig from a string.

Add from_config to PacketConfig

---

openc3/lib/openc3/packets/commands.rb
openc3/lib/openc3/packets/packet.rb
openc3/python/openc3/packets/commands.py
openc3/python/openc3/packets/packet.py
openc3/python/test/packets/test_commands.py
openc3/python/test/packets/test_packet_config.py
openc3/spec/api/cmd_api_spec.rb
openc3/spec/models/cvt_model_spec.rb
openc3/spec/models/microservice_model_spec.rb
openc3/spec/models/plugin_model_spec.rb
openc3/spec/packets/commands_spec.rb
openc3/spec/packets/packet_spec.rb
playwright/tests/command-sender.spec.ts

closes #1471 
Wait until COSMOS 6 to merge this behavior change.

cmd and cmd_raw raise on bad item states

---

openc3/lib/openc3/packets/commands.rb
openc3/lib/openc3/packets/packet.rb
openc3/python/openc3/packets/commands.py
openc3/python/openc3/packets/packet.py
openc3/python/test/packets/test_commands.py
openc3/python/test/packets/test_packet_config.py
openc3/spec/api/cmd_api_spec.rb
openc3/spec/models/cvt_model_spec.rb
openc3/spec/models/microservice_model_spec.rb
openc3/spec/models/plugin_model_spec.rb
openc3/spec/packets/commands_spec.rb
openc3/spec/packets/packet_spec.rb
playwright/tests/command-sender.spec.ts

Revert "cmd and cmd_raw raise on bad item states"

---

openc3/lib/openc3/script/web_socket_api.rb
openc3/lib/openc3/utilities/authentication.rb
openc3/python/openc3/script/web_socket_api.py
openc3/python/openc3/utilities/authentication.py

Fixes differences between Open Source and Enterprise

Make Bearer optional in token to fix web_socket_api

---

openc3/lib/openc3/packets/commands.rb
openc3/lib/openc3/packets/packet.rb
openc3/python/openc3/packets/commands.py
openc3/python/openc3/packets/packet.py
openc3/python/test/packets/test_commands.py
openc3/python/test/packets/test_packet_config.py
openc3/spec/api/cmd_api_spec.rb
openc3/spec/models/cvt_model_spec.rb
openc3/spec/models/microservice_model_spec.rb
openc3/spec/models/plugin_model_spec.rb
openc3/spec/packets/commands_spec.rb
openc3/spec/packets/packet_spec.rb
playwright/tests/command-sender.spec.ts

Enforces only defined states unless using cmd_no_range_check
closes #1471

Command State Range Checking for COSMOS 6

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-bucketexplorer/src/tools/BucketExplorer/BucketExplorer.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/LogMessages.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/OutputDialog.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/ace/EditorModes.js
openc3/spec/logs/buffered_packet_log_writer_spec.rb
playwright/tests/bucket-explorer.spec.ts

closes #1264
closes #1679 
closes #1680

BucketExplorer view files and breadcrumb paths

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/RunningScripts.vue
playwright/tests/bucket-explorer.spec.ts
playwright/tests/global.setup.ts
playwright/tests/script-runner/script-menu.spec.ts
playwright/tests/utc-time.spec.ts

Mostly small changes, plus fixing the app wrapper in enterprise itself

Fix tests for enterprise

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/CmdTlmServer.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/RawDialog.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/Updater.js
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/CriticalCmdDialog.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/EditScreenDialog.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/EditDialog.vue

This fixes the following issues with the raw dialog on cmdtlmserver:
- z-indexes underneath the sticky header of the log messages table
- resizing allows you to shrink it too small and hide the toolbar

Fix RawDialog behavior

---

openc3-cosmos-cmd-tlm-api/app/controllers/model_controller.rb
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/ToolsTab.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/AppNav.vue

Also handle bad URLs in ToolsTab and AppNav.
Any exception raised in a model.rb and not explicitly handled will just result in a 500 error. I recently made a change to `tool_model.rb` in #1701 that checks the URL and raises if it is bad. This just resulted in an unknown 500 error before the change but now shows a popup with the error message.

Handle exceptions in ModelController

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-http-example/README.md
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PackagesTab.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PluginsTab.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/calendar/Dialogs/ActivityCreateDialog.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/calendar/Dialogs/MetadataCreateDialog.vue
openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/calendar/Dialogs/NoteCreateDialog.vue
openc3.code-workspace
openc3/templates/plugin/README.md
playwright/tests/admin/plugins.spec.ts
playwright/tests/script-runner/api.spec.ts

Change plugin / package install to a button

---

openc3-cosmos-init/plugins/packages/openc3-tool-base/src/router.js
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/base/AppNav.vue

I'm not sure what changed... This basically reverts what I did during the vue 3 migration since the `replaceState` solution from COSMOS 5 wasn't working back then. (Looks like Enterprise never got this, and it's happy)

Fix redirect from root path

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/src/BigWidget.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/TargetsTab.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataextractor/src/tools/DataExtractor/DataExtractor.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataviewer/src/tools/DataViewer/AddComponentDialog.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataviewer/src/tools/DataViewer/DataViewer.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/OverridesDialog.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/SuiteRunner.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tablemanager/src/tools/TableManager/TableManager.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/TlmViewer.vue
openc3-cosmos-init/plugins/packages/openc3-tool-base/src/App.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/GraphEditDialog.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/TargetPacketItemChooser.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/DownloadDialog.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/InterfacesTab.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/MicroservicesTab.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/PackagesTab.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/PluginsTab.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/RoutersTab.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/SecretsTab.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/TargetsTab.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/ToolsTab.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/calendar/ActivityCreateDialog.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/LedWidget.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/LimitsbarWidget.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/ValueWidget.vue

Two tooltip bugs in LedWidget and LimitsbarWidget. Moved all tooltip to the top for consistency. Added some no_gutter to Command Sender and TargetPacketItemChooser to prevent a permanent horizontal scroll bar due to `style="overflow: auto"` in App.vue

Popups and horizontal scroll

---

openc3-cosmos-cmd-tlm-api/app/controllers/metadata_controller.rb
openc3-cosmos-cmd-tlm-api/app/controllers/notes_controller.rb
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/calendar/ColorSelectForm.vue

I'm going to leave this open until I finish Calendar testing

Better log message in note and metadata controller, fix ColorSelectForm

---

openc3-cosmos-cmd-tlm-api/app/controllers/timeline_controller.rb
openc3-cosmos-cmd-tlm-api/config/routes.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/timeline_controller_spec.rb
openc3/lib/openc3/models/timeline_model.rb

This is similar to how we recently added `shard`. Do we need a migration or since it is a new attribute none is needed?

Add execute to TimelineModel and api in controller to set it

---

openc3-cosmos-script-runner-api/scripts/run_suite_analysis.py

Fix import script in python suite

---

docs.openc3.com/docs/guides/scripting-api.md
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/LedWidget.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/RollupWidget.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/SignalWidget.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/VerticalWidget.vue

Add computedStyle to ROLLUP, LED, and SIGNAL widgets

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/procedures/screens.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/procedures/screens.py
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/GraphEditItemDialog.vue
playwright/tests/script-runner/api.spec.ts

Fix display screen 

---

openc3-cosmos-init/plugins/packages/openc3-tool-base/public/index-allow-http.html
openc3-cosmos-init/plugins/packages/openc3-tool-base/public/index.html
openc3-cosmos-init/plugins/packages/openc3-tool-base/public/js/browsercheck.js

closes https://github.com/OpenC3/cosmos/issues/1762

Alert for unsupported browsers

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/FileDialog.vue
playwright/tests/script-runner/prompts.spec.ts

I'm not 100% sure how this worked before... Maybe Vue 2 had some weird behavior with undefined v-models or something? This v-form was also missing any validation rules anyway

Fix ScriptRunner open_file_dialog

---

openc3-cosmos-cmd-tlm-api/app/controllers/news_controller.rb
openc3-cosmos-cmd-tlm-api/config/routes.rb
openc3-cosmos-init/plugins/README.md
openc3-cosmos-init/plugins/packages/openc3-js-common/src/services/openc3Api.js
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/SettingsTab.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/settings/NewsFeedSettings.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/settings/SuppressedSettings.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/settings/settings.js
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/base/UserMenu.vue
openc3/lib/openc3/api/settings_api.rb
openc3/lib/openc3/microservices/periodic_microservice.rb
openc3/lib/openc3/migrations/20250108060000_news_feed.rb
openc3/lib/openc3/models/news_model.rb
openc3/lib/openc3/models/scope_model.rb

Pulls news from https://github.com/OpenC3/openc3-news into the backend using the `PeriodicMicroservice` which updates once per day. This pulls news from the backend every hour since we don't know when the backend news will be updated.

Post news feed to user menu

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-ace-diff/src/helpers/merge.js

Fixes [https://github.com/OpenC3/cosmos/security/code-scanning/234](https://github.com/OpenC3/cosmos/security/code-scanning/234)
To fix the prototype pollution issue, we need to ensure that the `merge` function does not allow properties like `__proto__` and `constructor` to be merged. This can be achieved by adding checks to skip these properties during the merge process.
- We will modify the `merge` function to include checks that skip the `__proto__` and `constructor` properties.
- Specifically, we will add a condition to the loop that iterates over the keys of the `source` object to skip these properties.
- This change will be made in the `openc3-cosmos-init/plugins/packages/openc3-cosmos-ace-diff/src/helpers/merge.js` file.
_Suggested fixes powered by Copilot Autofix. Review carefully …

Fix code scanning alert no. 234: Prototype-polluting function

---

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/LedWidget.vue
openc3/data/config/widgets.yaml

Blur LedWidgets when stale

---

openc3/python/openc3/packets/telemetry.py

The method was attempting to iterate over target_packets using tuple unpacking, but `.items()` was missing from the dict iteration. This would cause a TypeError since Python dictionaries require `.items()` for key-value pair iteration.
Changed:
`for _, packet in target_packets:`
to:
`for _, packet in target_packets.items():`
This ensures proper dictionary key-value pair iteration when identifying packets in tlm_unique_id_mode.

fix(packets): correct dict iteration syntax in Telemetry.identify_packet

---

openc3-cosmos-init/plugins/packages/openc3-tool-base/public/index-allow-http.html
openc3-cosmos-init/plugins/packages/openc3-tool-base/public/index.html
openc3-cosmos-init/plugins/packages/openc3-tool-base/public/js/fixImoStyle.js
openc3-cosmos-init/plugins/packages/openc3-tool-base/src/assets/stylesheets/layout/_overrides.scss

They changed to putting everything in the shadow DOM, which means we can't style it directly from our stylesheets anymore. Dialog text was unreadable due to it using the default `color: canvastext;` from the user-agent sheet for dialogs, which is `rgb(255,255,255)`. I think their [demo](https://user-images.githubusercontent.com/5524384/77237035-07476600-6b8a-11ea-9041-8b70f633d5d0.gif) still works because of differing themes.
Before:
After:

Fix import-map-overrides dialog style

---

openc3/lib/openc3/packets/parsers/packet_item_parser.rb
openc3/openc3.gemspec
openc3/python/openc3/packets/parsers/packet_item_parser.py
openc3/python/test/packets/parsers/test_packet_item_parser.py
openc3/spec/packets/parsers/packet_item_parser_spec.rb

Properly parse hex and binary ID items

---

openc3-cosmos-cmd-tlm-api/app/models/table.rb
openc3-cosmos-cmd-tlm-api/spec/models/table_spec.rb

Improve TableManager definition lookup

---

.env
openc3-cosmos-script-runner-api/app/models/running_script.rb
openc3-cosmos-script-runner-api/scripts/running_script.py

Eliminate script zombies. Fix python output thread. Default CI to empty string

---

openc3/python/openc3/interfaces/tcpip_server_interface.py

Add exception catch on python hostname lookup

---

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/TitleWidget.vue

Closes https://github.com/OpenC3/cosmos/issues/1923
Looks like spans won't take a full-width anymore in Vuetify 3 (which imo is correct behavior anyway)

Fix title widget centering

---

openc3/lib/openc3/api/settings_api.rb
openc3/lib/openc3/microservices/periodic_microservice.rb
openc3/lib/openc3/models/news_model.rb

Handle news connection failure

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/cmd_tlm/inst_cmds.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/cmd_tlm/inst_tlm.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/lib/sim_inst.rb
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/cmd_tlm/inst_cmds.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/cmd_tlm/inst_tlm.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/lib/sim_inst.py
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue
openc3-cosmos-init/plugins/packages/openc3-js-common/package.json
openc3-cosmos-init/plugins/packages/openc3-js-common/src/services/openc3Api.js
openc3/spec/api/router_api_spec.rb
playwright/tests/command-sender.spec.ts

Support 64 bit ints in CommandSender

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/utilities.js
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/autocomplete/screenCompleter.js
openc3-cosmos-script-runner-api/scripts/script_instrumentor.py
openc3-cosmos-script-runner-api/test/scripts/test_script_instrumentor.py
playwright/tests/utc-time.spec.ts

Fix python try except instrumentation

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/plugin.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/InterfacesTab.vue
openc3/lib/openc3/api/interface_api.rb
openc3/python/openc3/api/interface_api.py
openc3/python/test/api/test_interface_api.py
openc3/spec/api/interface_api_spec.rb
playwright/tests/cmd-tlm-server/interfaces.spec.ts

Fix DISABLE_DISCONNECT in the frontend

---

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/plugins/dialog/ConfirmDialog.vue

If you opened a dialog where you inputted validation text, subsequent non-validation-text dialogs on that page wouldn't work

Fix bug in confirm dialog with validation text

---

openc3-cosmos-cmd-tlm-api/app/channels/autonomic_events_channel.rb
openc3-cosmos-cmd-tlm-api/app/channels/calendar_events_channel.rb
openc3-cosmos-cmd-tlm-api/app/channels/config_events_channel.rb
openc3-cosmos-cmd-tlm-api/app/channels/limits_events_channel.rb
openc3-cosmos-cmd-tlm-api/app/channels/messages_channel.rb
openc3-cosmos-cmd-tlm-api/app/channels/streaming_channel.rb
openc3-cosmos-cmd-tlm-api/app/channels/system_events_channel.rb
openc3-cosmos-cmd-tlm-api/app/channels/timeline_events_channel.rb
openc3-cosmos-cmd-tlm-api/app/models/autonomic_events_api.rb
openc3-cosmos-cmd-tlm-api/app/models/calendar_events_api.rb
openc3-cosmos-cmd-tlm-api/app/models/config_events_api.rb
openc3-cosmos-cmd-tlm-api/app/models/limits_events_api.rb
openc3-cosmos-cmd-tlm-api/app/models/messages_api.rb
openc3-cosmos-cmd-tlm-api/app/models/messages_thread.rb
openc3-cosmos-cmd-tlm-api/app/models/streaming_api.rb
openc3-cosmos-cmd-tlm-api/app/models/system_events_api.rb
openc3-cosmos-cmd-tlm-api/app/models/timeline_events_api.rb
openc3-cosmos-cmd-tlm-api/app/models/topics_thread.rb
openc3-cosmos-cmd-tlm-api/spec/channels/streaming_channel_spec.rb
openc3-cosmos-cmd-tlm-api/spec/models/streaming_api_spec.rb

LimitsMonitor had two channels on the same cable, which was causing problems because they were both using the same uuid.  This change will allow for different channels on the same cable.

Fix multiple subscriptions on the same connection

---

playwright/playwright.config.ts

Tests are timing out esp. on enterprise. Hopefully this bump is enough for the github runners

Increase test timeouts

---

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue

Wrapping it in an extraneous div broke a css selector

Fix script runner size

---

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/LedWidget.vue

Add details dialog to LedWidget

---

openc3-traefik/Dockerfile
scripts/linux/openc3_build_ubi.sh

I'm mostly interested to see if this closes the Traefik CVE

Bump traefik to 3.3.5

---

openc3/python/openc3/utilities/logger.py
openc3/python/openc3/utilities/store_implementation.py
openc3/python/test/utilities/test_logger.py
openc3/python/test/utilities/test_store_implementation.py

Fix python help()

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-bucketexplorer/src/tools/BucketExplorer/BucketExplorer.vue

Previously the slash and the space around the slash was clickable which caused weird issues if you clicked it. I also fixed a bug when uploading to the root where it would append an extra slash.

Don't make path clickable in Bucket Explorer

---

openc3-cosmos-init/plugins/packages/openc3-tool-base/src/router.js
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/base/AppNav.vue

This fixes the issue where going to the route `'/'` did not reliably redirect you to the first tool. I don't want this redirect to get hung up on a slow API response, so I added a timeout of 150ms before it gives up and goes to a hardcoded cmdtlmserver
Looks like this also fixes [this todo](https://github.com/OpenC3/cosmos/blob/4641f87651947a917c677512aaf0dcffc8102abc/openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/base/AppNav.vue#L346-L349).
Will also need the same change made in Enterprise once this PR is approved

Move root redirect to nav guard

---

openc3-cosmos-cmd-tlm-api/config/environments/test.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/api_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/info_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/microservices_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/packages_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/process_status_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/reaction_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/redis_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/scopes_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/secrets_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/storage_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/tables_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/time_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/tools_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/trigger_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/controllers/users_controller_spec.rb
openc3-cosmos-cmd-tlm-api/spec/spec_helper.rb

- Improving testing coverage on the Cmd-Tlm-API
- Code Coverage increased by ~22.6% on this Plugin
- Silenced logging while running tests for better testing experience
- I'm using the "Standard Ruby" Extension for code formatting, if you all dislike it, let me know 👍

[Unit Tests] - Cmd / Tlm Controllers

---

openc3-cosmos-script-runner-api/config/environments/test.rb
openc3-cosmos-script-runner-api/spec/controllers/running_script_controller_spec.rb
openc3-cosmos-script-runner-api/spec/controllers/scripts_controller_spec.rb
openc3-cosmos-script-runner-api/spec/models/running_script_spec.rb
openc3-cosmos-script-runner-api/spec/models/script_spec.rb

Increases code coverage on Script Runner API to 64.2% (+38.5%). 
Some of the code in `running_script.rb` requires heavy stubbing, looking to address that separately.
`running_script.rb` is quite a large file, and I was following the convention of One Ruby file -> One Spec file, but if you'd like me to break it out, please let me know!

[Unit Tests] - Script Runner API

---

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/plugins/notify/Toast.vue

This way it's just `{title}` instead of `{title}:`. The `:` is still there when there's a body

Remove extra : in toast notification when there's no body

---

openc3-cosmos-init/Dockerfile

also solves an issue where sometimes multiple base gem files would be copied in, putting init into a crash loop

Rebalance init image build

---

openc3-cosmos-cmd-tlm-api/.rspec
openc3-cosmos-cmd-tlm-api/spec/models/topics_thread_spec.rb

Two changes:
- As part of topics_thread_spec.rb, I previously added a define_singleton_method on OpenC3::Topic. Since rspec tests are run in random order, with particular orders this had a side effect on other tests. Didn't end up being necessary, so removed
- Updated the test to instead of defining OpenC3::Topic stub method `xrevrange`, stubbed the call that is ultimately made to redis instead (as OpenC3::Topic delegates missing methods, but this is transparent to RSpec so this is the cleaner workaround)

Fix Cmd Tlm API Unit Tests

---

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/EditScreenDialog.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Openc3Screen.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/VerticalWidget.vue

Items were not being cleared when a screen is rendered, meaning that if you added an item that doesn't exist, the error alerting you to that fact would persist until you completely closed and reopened the screen (even after removing the bad item from the screen definition and clicking "save"). Clearing out `screenItems` when the screen definition is parsed fixes this, so all you have to do to clear the error is save the screen:

Clear screenItems when re-parsing screen definition

---

openc3-cosmos-init/plugins/packages/openc3-tool-base/src/router.js

Clone changes from https://github.com/OpenC3/cosmos-enterprise/pull/264 in enterprise. This issue is not present in Core (as Keycloak is not here) but still cloning the same short-circuit logic for continuity.

Fix Firefox infinite redirect issue

---

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/SpacerWidget.vue

These were getting skipped because `appliedSettings` is calculated in Widget.js' `created()`, so SpacerWidget always just got the default flex styling since v6.0.0

Fix SpacerWidget parameters

---

openc3/lib/openc3/models/target_model.rb
openc3/python/openc3/models/target_model.py

This should reset the telemetry and command counts when a plugin is uninstalled.

Reset the Tlm and Cmd Counts on Undeploy

---

.github/workflows/generate-docs.yml

Existing action wasn't working as the action didn't have permission to push to `main`. Mimicking the implementation in: https://github.com/OpenC3/cosmos/blob/main/.github/workflows/release.yml
to check out with a PAT so that push is allowed

Auto-Generate Docs when changes detected -- Add PAT for main push

---

openc3/lib/openc3/utilities/aws_bucket.rb
openc3/lib/openc3/utilities/bucket.rb
openc3/python/openc3/utilities/aws_bucket.py
openc3/python/openc3/utilities/bucket.py
openc3/spec/local_s3.rb
openc3/spec/utilities/local_mode_spec.rb

The following get_object lookups have been tested with Minio and AWS S3:
```
**PYTHON**
from openc3.utilities.bucket import Bucket
client = Bucket.getClient()
response = client.get_object(bucket="config", key="DEFAULT/targets_modified/test.csv", range="bytes=1-10")
print(response["Body"].read())
from openc3.utilities.bucket import Bucket
client = Bucket.getClient()
response = client.get_object(bucket="config", key="DEFAULT/targets_modified/test.csv")
print(response["Body"].read())
```
```
**RUBY**
client = OpenC3::Bucket.getClient
response = client.get_object(bucket: "config", key: "DEFAULT/targets_modified/test.csv", range: "bytes=1-10")
puts response.body.read
client = OpenC3::Bucket.getClient
response = client.get_object(bucket: "config", key: "DEFAULT/targets_modified/test.csv")
puts …
```

Add `range` arg option to get_object calls

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/TlmViewer.vue

Closes #2159 
Adds autocomplete type-ahead (similar to command sender) to the dropdowns for Tlm Viewer

Add autocomplete to Tlm Viewer dropdowns

---

openc3-cosmos-script-runner-api/app/controllers/running_script_controller.rb
openc3-cosmos-script-runner-api/spec/controllers/running_script_controller_spec.rb

Command Authority has been broken since [6.4.0](https://github.com/OpenC3/cosmos/releases/tag/v6.4.0) due to our processing name instead of filename when determining the target to check against.

Fix script authorization for Command Authority

---

openc3-traefik/traefik-allow-http.yaml
openc3-traefik/traefik-letsencrypt.yaml
openc3-traefik/traefik-ssl.yaml
openc3-traefik/traefik.yaml

closes https://github.com/OpenC3/cosmos/issues/2182
The index router was matching e.g. `/tools/staticdocs/docs/tools/bucket-explorer` because there is another `/` after `static.*`. This makes the regex stricter so that route goes to the correct middleware (adding `.html` instead of `/index.html`)

Fix static routes

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/cmd_tlm/inst_cmds.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/cmd_tlm/inst_tlm.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/lib/sim_inst.py
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/screens/commanding.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/screens/params.txt
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/router.js
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/CmdPacketsTab.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/TlmPacketsTab.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-handbooks/src/router.js
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsEvents.vue
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-packetviewer/src/router.js
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/router.js
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/LedWidget.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/VWidget.js
openc3-traefik/traefik-allow-http.yaml
openc3-traefik/traefik-letsencrypt.yaml
openc3-traefik/traefik-ssl.yaml
openc3-traefik/traefik.yaml
playwright/tests/cmd-tlm-server/cmd-pkts.p.spec.ts
playwright/tests/command-sender.p.spec.ts
playwright/tests/data-extractor.p.spec.ts
playwright/tests/packet-viewer.p.spec.ts
playwright/tests/utc-time.p.spec.ts
playwright/utilities.ts

Fix traefik routing

---

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-bucketexplorer/src/tools/BucketExplorer/BucketExplorer.vue
openc3-cosmos-init/plugins/packages/openc3-js-common/src/utils/formatter.js

closes #2255 
Converts the Byte column to be more "human readable"

Add formatting on byte column for Bucket Explorer

---

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/RedisTab.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/Dialogs/InformationDialog.vue

I use the redis tab all the time and this has been bugging me so hard lol
Before:
After:

Add pretty-print feature to redis tab

---

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/FileOpenSaveDialog.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/TargetPacketItemChooser.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/TreeNode.vue
openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue

closes #2259 
closes #2222 
Added tooltips, widened dialogs, and added CSS to handle particularly long packet names / file names.

Improve handling of long file names

---

docs.openc3.com/docs/guides/troubleshooting.md
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue

closes #2272 
@ryanmelt Not sure why you changed this but if you have a target with no commands this effectively disables the command selection permanently.

Do not disable command chooser when command name is null

---

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue

If this API request returned an error (e.g. you did a cleanup and that running script no longer existed), SR would lock up and you couldn't recover it without hacking up your storage.

Handle API error on Script Runner page load

---

openc3/python/openc3/utilities/running_script.py

Because we were setting `.filename` on the type and it got set in each loop iteration, every `NamedTemporaryFile.filename()` would always return the last filename in `input`. There might still be a cleaner way to do this, but you're not really supposed to define arbitrary methods on python objects, so... at least this works now

Fix uploaded filename in script

---

docs.openc3.com/openc3-cosmos-tool-docs.gemspec
examples/openc3-cosmos-accessor-test/openc3-cosmos-accessor-test.gemspec
examples/openc3-cosmos-erb-test/openc3-cosmos-erb-test.gemspec
examples/openc3-cosmos-http-example/openc3-cosmos-http-example.gemspec
examples/openc3-cosmos-mqtt-test/openc3-cosmos-mqtt-test.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/openc3-cosmos-demo.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-admin/openc3-cosmos-tool-admin.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-bucketexplorer/openc3-cosmos-tool-bucketexplorer.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/openc3-cosmos-tool-cmdsender.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/openc3-cosmos-tool-cmdtlmserver.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataextractor/openc3-cosmos-tool-dataextractor.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataviewer/openc3-cosmos-tool-dataviewer.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-handbooks/openc3-cosmos-tool-handbooks.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-iframe/openc3-cosmos-tool-iframe.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/openc3-cosmos-tool-limitsmonitor.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-packetviewer/openc3-cosmos-tool-packetviewer.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/openc3-cosmos-tool-scriptrunner.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tablemanager/openc3-cosmos-tool-tablemanager.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/openc3-cosmos-tool-tlmgrapher.gemspec
openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/openc3-cosmos-tool-tlmviewer.gemspec
openc3-cosmos-init/plugins/packages/openc3-tool-base/openc3-tool-base.gemspec
openc3/openc3.gemspec
openc3/templates/plugin/plugin.gemspec

There is a warning when you create gems:
```
WARNING:  make sure you specify the oldest ruby version constraint (like ">= 3.0") that you want your gem to support by setting the `required_ruby_version` gemspec attribute
```
So this adds `s.required_ruby_version = '>= 3.0'` to all the gemspecs

Set required_ruby_version in all gemspecs

---

openc3/lib/openc3/io/json_rpc.rb

This change in json https://github.com/ruby/json/pull/833 requires you to now `require 'json/add/string'` before you can call the various methods on the String object. Since [v2.14.0](https://github.com/ruby/json/releases/tag/v2.14.0).

require 'json/add/string'

---

openc3/lib/openc3/models/plugin_model.rb
openc3/spec/models/plugin_model_spec.rb

Closes https://github.com/OpenC3/cosmos/issues/2282
Instead of names like `openc3-cosmos-bob-1.0.1.gem__20250904175756`, they now increment with a counter like `openc3-cosmos-bob-1.0.1.gem__3`. Deleting one or more instances in the middle of the sequence and re-installing will fill that gap back in the sequence and then continue as expected. This is backwards compatible with the current timestamp based naming (see unit tests).
If it's more desirable to just continue after the highest counter value and don't fill in the gap, that's an easy change.
1. Create an example plugin by following the [getting started guide](https://docs.openc3.com/docs/getting-started/gettingstarted)
2. Install the same gem bundle multiple times (but make the target unique)
3. Verify expected naming behavior
``` …
```

Make plugin instance names repeatable #2282
