examples/external_script.rb, openc3-script-runner-api/config/initializers/authorization.rb, openc3-script-runner-api/config/routes.rb, openc3-script-runner-api/spec/spec_helper.rb, openc3/lib/openc3/io/json_api_object.rb, openc3/lib/openc3/io/json_drb_object.rb, openc3/lib/openc3/script/calendar.rb, openc3/lib/openc3/script/script.rb, openc3/lib/openc3/script/script_runner.rb
Also Removed Long Delay API retries
closes #6
=> Script Authentication Enforced. Added Script Runner Ruby Client. 

openc3/lib/openc3/top_level.rb
=> Add COSMOS compatibility code

openc3-cmd-tlm-api/app/controllers/api_controller.rb, openc3-cmd-tlm-api/app/models/screen.rb, openc3-cmd-tlm-api/config/routes.rb, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/CanvasWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/DynamicWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/HorizontalWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/LabelWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/LabelvalueWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/MatrixbycolumnsWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/TabbookWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/ValueWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/VerticalWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/Widget.js, openc3-init/plugins/packages/openc3-tool-common/src/services/config-parser.js, openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/EditScreenDialog.vue, openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/NewScreenDialog.vue, openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/Openc3Screen.vue, openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/TlmViewer.vue, playwright/tests/tlm-viewer.spec.ts
=> New screen

openc3-script-runner-api/app/models/running_script.rb, openc3/lib/openc3/script/calendar.rb, openc3/lib/openc3/script/commands.rb, openc3/lib/openc3/script/limits.rb, openc3/lib/openc3/script/script.rb, openc3/lib/openc3/script/script_runner.rb, openc3/lib/openc3/script/storage.rb, openc3/spec/script/limits_spec.rb
=> script support scope for all methods

openc3.bat, openc3.sh, openc3/bin/openc3cli
=> Allow --user=root to openc3cli

openc3/lib/openc3/script/api_shared.rb, openc3/spec/script/api_shared_spec.rb
=> Better check message and help with NameError

openc3/lib/openc3/conversions/conversion.rb, openc3/lib/openc3/conversions/generic_conversion.rb, openc3/lib/openc3/conversions/polynomial_conversion.rb, openc3/lib/openc3/conversions/processor_conversion.rb, openc3/lib/openc3/conversions/segmented_polynomial_conversion.rb, openc3/lib/openc3/conversions/unix_time_conversion.rb, openc3/spec/conversions/generic_conversion_spec.rb, openc3/spec/conversions/processor_conversion_spec.rb
=> Add converted_ state to as_json

openc3.bat, openc3.code-workspace, openc3.sh, scripts/linux/openc3_deploy.sh, scripts/windows/openc3_deploy.bat
Unfortunately ./openc3.sh cli is probably broken until we merge/release this.
=> fix typoes and references

openc3/lib/openc3/models/scope_model.rb, openc3/spec/models/scope_model_spec.rb
=> Create UNKNOWN target in scope_model

openc3-init/plugins/openc3-tool-base/yarn.lock, openc3-init/plugins/packages/openc3-demo/targets/INST/screens/graphs.txt, openc3-init/plugins/packages/openc3-tool-common/src/components/Graph.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/LabelsparklineWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/SparklineWidget.vue, openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/EditScreenDialog.vue, openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/Openc3Screen.vue, openc3/data/config/widgets.yaml
=> Fix linegraph widget and add sparkline

openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/ArrayWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/BlockWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/TextboxWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/VWidget.js, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/ValueWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/plugins/store.js, openc3-init/plugins/packages/openc3-tool-packetviewer/src/tools/PacketViewer/PacketViewer.vue, openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/Openc3Screen.vue
=> ValueWidget telemetry aging

openc3-init/plugins/packages/openc3-tool-autonomic/plugin.txt, openc3-init/plugins/packages/openc3-tool-calendar/plugin.txt, openc3-init/plugins/packages/openc3-tool-cmdsender/plugin.txt, openc3-init/plugins/packages/openc3-tool-cmdtlmserver/plugin.txt, openc3-init/plugins/packages/openc3-tool-dataextractor/plugin.txt, openc3-init/plugins/packages/openc3-tool-dataviewer/plugin.txt, openc3-init/plugins/packages/openc3-tool-handbooks/plugin.txt, openc3-init/plugins/packages/openc3-tool-limitsmonitor/plugin.txt, openc3-init/plugins/packages/openc3-tool-packetviewer/plugin.txt, openc3-init/plugins/packages/openc3-tool-scriptrunner/plugin.txt, openc3-init/plugins/packages/openc3-tool-tablemanager/plugin.txt, openc3-init/plugins/packages/openc3-tool-tlmgrapher/plugin.txt, openc3-init/plugins/packages/openc3-tool-tlmviewer/plugin.txt, openc3/data/config/command_modifiers.yaml, openc3/data/config/tool.yaml, openc3/lib/openc3/models/tool_model.rb
=> Add POSITION keyword for tools

openc3/lib/openc3/operators/microservice_operator.rb, openc3/lib/openc3/operators/operator.rb, openc3/spec/operators/operator_process_spec.rb
=> Print operator cmd in log

openc3/lib/openc3/models/cvt_model.rb
=> Move CvtModel back to Persistent Redis Store

openc3/lib/openc3/packets/parsers/xtce_parser.rb, openc3/spec/packets/parsers/xtce_parser_spec.rb
=> Implement additional xtce keywords

compose.yaml, openc3-init/plugins/README.md, openc3-minio/Dockerfile, openc3-traefik/Dockerfile, openc3-traefik/traefik-allow-http.yaml, openc3-traefik/traefik-dev-base.yaml, openc3-traefik/traefik-dev.yaml, openc3-traefik/traefik-letsencrypt.yaml, openc3-traefik/traefik-ssl.yaml, openc3-traefik/traefik.yaml, scripts/release/package_audit.rb
=> Upgrade to latest minio

openc3-init/plugins/packages/openc3-demo/targets/INST/screens/commanding.txt, openc3-init/plugins/packages/openc3-tool-common/src/components/widgets/ButtonWidget.vue, openc3-init/plugins/packages/openc3-tool-common/src/services/openc3-api.js, openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/TlmViewer.vue
=> Full tlm api support

openc3-init/plugins/packages/openc3-tool-common/src/components/FileOpenSaveDialog.vue, openc3-script-runner-api/app/controllers/scripts_controller.rb
=> Suite detection

lib/cosmos/api/cmd_api.rb, openc3-init/plugins/packages/openc3-demo/targets/INST/cmd_tlm/inst_cmds.txt, openc3-init/plugins/packages/openc3-tool-cmdsender/src/tools/CommandSender/CommandParameterEditor.vue, openc3-init/plugins/packages/openc3-tool-cmdsender/src/tools/CommandSender/CommandSender.vue, openc3-init/plugins/packages/openc3-tool-common/src/components/TargetPacketItemChooser.vue, openc3/lib/openc3/api/cmd_api.rb
=> CmdSender state in history and hazardous indicator

openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/EditScreenDialog.vue
=> Fix tlm viewer screen upload

openc3-cmd-tlm-api/app/controllers/api_controller.rb, openc3-cmd-tlm-api/app/controllers/tables_controller.rb, openc3-init/plugins/packages/openc3-tool-cmdsender/src/tools/CommandSender/CommandSender.vue, openc3-init/plugins/packages/openc3-tool-common/src/services/axios.js, openc3-init/plugins/packages/openc3-tool-common/src/services/openc3-api.js, openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue, openc3-init/plugins/packages/openc3-tool-tablemanager/src/tools/TableManager/TableManager.vue
=> Implement header based interceptor control

openc3-init/plugins/packages/openc3-demo/targets/INST/procedures/file_dialog.rb, openc3-script-runner-api/app/models/running_script.rb, openc3/lib/openc3/core_ext/tempfile.rb, openc3/lib/openc3/script/storage.rb
=> Add filename to Tempfile returned by open_file_dialog

openc3-init/plugins/packages/openc3-tool-common/src/services/openc3-api.js, openc3/lib/openc3/api/interface_api.rb
Support an array of target_names
Add map_target_to_interface to javascript api
closes #162
=> map_target_to_interface updates

openc3/lib/openc3/utilities/s3.rb, openc3/lib/openc3/utilities/s3_autoload.rb
=> Make Aws autoload only apply to S3

openc3/lib/openc3/interfaces/interface.rb
=> read client count from function rather than variable

openc3/lib/openc3/script/storage.rb
=> Fix put_target_file with IO and local mode

openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/Openc3Screen.vue
=> Set screen min height and width

openc3/lib/openc3/operators/operator.rb, openc3/spec/operators/operator_process_spec.rb
=> Reduce process output

openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/NewScreenDialog.vue, openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/TlmViewer.vue
=> Create new screen based on existing packet

openc3-init/plugins/packages/openc3-tool-common/src/components/Graph.vue
=> Allow user editing graph colors

openc3-init/plugins/packages/openc3-demo/targets/INST/cmd_tlm/inst_cmds.txt, openc3-init/plugins/packages/openc3-demo/targets/INST/lib/sim_inst.rb
=> Add QUIET command to demo

openc3-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PluginsTab.vue
=> Remove admin Download button

openc3-init/plugins/openc3-tool-base/openc3-tool-base.gemspec, openc3-init/plugins/packages/openc3-accessor-test/openc3-accessor-test.gemspec, openc3-init/plugins/packages/openc3-demo/openc3-demo.gemspec, openc3-init/plugins/packages/openc3-erb-test/openc3-erb-test.gemspec, openc3-init/plugins/packages/openc3-tool-admin/openc3-tool-admin.gemspec, openc3-init/plugins/packages/openc3-tool-autonomic/openc3-tool-timeline.gemspec, openc3-init/plugins/packages/openc3-tool-calendar/openc3-tool-timeline.gemspec, openc3-init/plugins/packages/openc3-tool-cmdsender/openc3-tool-cmdsender.gemspec, openc3-init/plugins/packages/openc3-tool-cmdtlmserver/openc3-tool-cmdtlmserver.gemspec, openc3-init/plugins/packages/openc3-tool-dataextractor/openc3-tool-dataextractor.gemspec, openc3-init/plugins/packages/openc3-tool-dataviewer/openc3-tool-dataviewer.gemspec, openc3-init/plugins/packages/openc3-tool-handbooks/openc3-tool-handbooks.gemspec, openc3-init/plugins/packages/openc3-tool-limitsmonitor/openc3-tool-limitsmonitor.gemspec, openc3-init/plugins/packages/openc3-tool-packetviewer/openc3-tool-packetviewer.gemspec, openc3-init/plugins/packages/openc3-tool-scriptrunner/openc3-tool-scriptrunner.gemspec, openc3-init/plugins/packages/openc3-tool-tablemanager/openc3-tool-tablemanager.gemspec, openc3-init/plugins/packages/openc3-tool-tlmgrapher/openc3-tool-tlmgrapher.gemspec, openc3-init/plugins/packages/openc3-tool-tlmviewer/openc3-tool-tlmviewer.gemspec, openc3/templates/plugin-template/plugin.gemspec
=> Remove procedures from gemspec

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/Openc3Screen.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/LimitsbarWidget.vue
=> Fix edit screen and 0 values

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/screens/commanding.txt, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/screens/launcher.txt, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/Openc3Screen.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/TlmViewer.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/ButtonWidget.vue, openc3/data/config/screen.yaml, openc3/data/config/widgets.yaml
=> Add open and close methods for screen

openc3/lib/openc3/api/tlm_api.rb, openc3/lib/openc3/script/script.rb, openc3/lib/openc3/script/telemetry.rb
=> Move get_packets blocking to client

openc3/lib/openc3/logs/buffered_packet_log_writer.rb, openc3/lib/openc3/logs/log_writer.rb, openc3/lib/openc3/logs/packet_log_writer.rb, openc3/lib/openc3/microservices/log_microservice.rb, openc3/lib/openc3/microservices/reducer_microservice.rb, openc3/lib/openc3/microservices/text_log_microservice.rb
=> Clean shutdown for TextLogMicroservice. Don't enforce time ordering for text logs

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/AskDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/FileDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/InformationDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/PromptDialog.vue
=> Support newlines in script dialogs

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/procedures/checks.rb, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/screens/commanding.txt, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/EditScreenDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/NewScreenDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/ScreenOverviewDialog.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/ButtonWidget.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/services/config-parser.js, openc3-cosmos-script-runner-api/scripts/run_script.rb
=> Tlm viewer env to scripts

openc3-cosmos-cmd-tlm-api/app/controllers/api_controller.rb, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue, openc3/lib/openc3/io/json_api_object.rb, openc3/lib/openc3/io/json_drb.rb, openc3/lib/openc3/io/json_rpc.rb
=> Change hazardous error code

openc3.bat, openc3.sh
=> Switch from cli using base to operator

.github/workflows/playwright.yml, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PluginsTab.vue, openc3.sh, openc3/bin/openc3cli, openc3/lib/openc3/models/gem_model.rb, openc3/lib/openc3/models/interface_model.rb, openc3/lib/openc3/models/model.rb, openc3/lib/openc3/models/plugin_model.rb, openc3/lib/openc3/utilities/store_autoload.rb, openc3/spec/models/model_spec.rb
=> Validate screen names and gem install local

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/Openc3Screen.vue
=> Apply global subsettings along with global settings

openc3-cosmos-cmd-tlm-api/app/models/streaming_object_file_reader.rb, openc3/lib/openc3/logs/buffered_packet_log_reader.rb
=> Dont identify_and_define for StreamingApi

openc3-cosmos-script-runner-api/app/models/running_script.rb, openc3.code-workspace, openc3/lib/openc3/script/api_shared.rb
=> Enforce require only once

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/TargetPacketItemChooser.vue, scripts/release/build_multi_arch.sh
=> Remove UNKNOWN from target chooser

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/cmd_tlm/inst_cmds.txt, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandParameterEditor.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue
=> CmdSender display range, set default state value

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/TlmGrapher.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/DateTimeChooser.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue
=> Save graph start/stop times in config

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-packetviewer/src/tools/PacketViewer/PacketViewer.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/TopBar.vue
=> Hide ignored, derived last, and * derived

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/lib/sim_inst.rb
=> Fix unknown in demo

.github/workflows/release.yml
closes #362 
See: https://github.com/actions/runner/issues/1483
=> Fix github release if checks

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataextractor/src/tools/DataExtractor/DataExtractor.vue
=> Data Extractor DataTable instead of list

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/Openc3Screen.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/LogMessages.vue, openc3/data/config/table_manager.yaml
Fixes sending hazardous command parameters in raw mode
Better layout for Limits Monitor in small screen widths
Move TlmViewer screen edit icon to left to match TlmGrapher
Don't display overview graph when displaying half height graph
Handle binary data in LogMessages
=> Various fixes found during tool documentation updates

openc3/lib/openc3/script/suite.rb, openc3/spec/script/suite_spec.rb, openc3/spec/system/system_spec.rb, openc3/spec/tools/test_runner/test_spec.rb
=> Remove initialize from Suite and Group

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue, openc3-cosmos-script-runner-api/app/models/script.rb, openc3-cosmos-script-runner-api/spec/controllers/scripts_controller_spec.rb, openc3/lib/openc3/utilities/target_file.rb
=> Always save when starting script, clear breakpoints

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue, openc3-cosmos-script-runner-api/app/models/running_script.rb, openc3/lib/openc3/script/script.rb, openc3/lib/openc3/script/script_runner.rb
=> Only enable Step while running, add step_mode, run_mode, show_backtrace

openc3-cosmos-cmd-tlm-api/app/controllers/plugins_controller.rb, openc3.code-workspace, openc3/bin/openc3cli, openc3/templates/plugin-template/LICENSE.txt, openc3/templates/plugin-template/plugin.gemspec
=> Force install from Plugins tab, add MIT license to plugin template

openc3.bat, openc3.sh
=> Prompt for cleanup

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/DetailsDialog.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/services/openc3-api.js, openc3/lib/openc3/packets/packet_item.rb, openc3/spec/packets/packet_item_limits_spec.rb, openc3/spec/packets/packet_item_spec.rb
=> Enable limits from DetailsDialog

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/AppNav.vue
=> Easier to click nav

openc3/lib/openc3/microservices/interface_microservice.rb
=> Handle command only target

.env, compose.yaml, openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb, openc3-cosmos-init/plugins/openc3-tool-base/package.json, openc3-cosmos-init/plugins/openc3-tool-base/yarn.lock, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-bucketexplorer/src/tools/BucketExplorer/BucketExplorer.vue, openc3.bat, openc3/lib/openc3/utilities/aws_bucket.rb, openc3/lib/openc3/utilities/bucket.rb, openc3/spec/utilities/aws_bucket_spec.rb
=> Add additional buckets to .env file

openc3-cosmos-cmd-tlm-api/config/initializers/cts.rb, openc3/lib/openc3.rb, openc3/spec/core_ext/io_spec.rb, openc3/spec/interfaces/udp_interface_spec.rb, openc3/spec/streams/tcpip_socket_stream_spec.rb
=> add resolv-replace to help with alpine dns

openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-bucketexplorer/src/tools/BucketExplorer/BucketExplorer.vue, openc3/lib/openc3/utilities/authorization.rb
=> Implement upload and delete file

openc3-cosmos-cmd-tlm-api/app/channels/application_cable/channel.rb, openc3-cosmos-cmd-tlm-api/app/models/streaming_object.rb, openc3-cosmos-cmd-tlm-api/app/models/streaming_thread.rb, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-autonomic/src/tools/Autonomic/Tabs/Triggers/TriggerOperand.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/TlmGrapher.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/TargetPacketItemChooser.vue, openc3-cosmos-script-runner-api/app/channels/application_cable/channel.rb
=> Graph reduced

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-autonomic/src/tools/Autonomic/Tabs/Reactions/CreateDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-calendar/src/tools/Calendar/Dialogs/ActivityCreateDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-calendar/src/tools/Calendar/Dialogs/ActivityUpdateDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/ScriptEnvironmentDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/EnvironmentChooser.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/EnvironmentDialog.vue, openc3-cosmos-script-runner-api/app/models/running_script.rb, openc3-cosmos-script-runner-api/scripts/run_script.rb
=> Apply global and then script env vars

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PluginsTab.vue
=> Plugin install check existing name

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/plugin.txt, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/EXAMPLE/lib/my_reject_protocol.rb, openc3/data/config/item_modifiers.yaml, openc3/lib/openc3/interfaces/interface.rb, openc3/lib/openc3/microservices/interface_microservice.rb
=> Support rejecting commands from interface / protocols without disconnecting interface

openc3/bin/openc3cli, openc3/lib/openc3/bridge/bridge.rb, openc3/lib/openc3/bridge/bridge_config.rb
closes #497 
closes #354 
closes #303 
Example bridges:
https://github.com/OpenC3/openc3-cosmos-bridge-serial
https://github.com/OpenC3/openc3-cosmos-bridge-hidapi
https://github.com/OpenC3/openc3-cosmos-bridge-dualsense
Bridge documentation: https://openc3.com/docs/v5/bridges
=> Bridge updates for bridgegem system

openc3/bin/openc3cli
closes #494 
I borrowed this code from what you have in the `files` method in `storage_controller.rb`. Although I combined the two maps into a single one.
=> Init all defined buckets on startup

openc3-cosmos-cmd-tlm-api/app/controllers/gems_controller.rb, openc3-cosmos-cmd-tlm-api/config/routes.rb, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PluginsTab.vue
=> Download plugin

openc3-cosmos-cmd-tlm-api/app/controllers/plugins_controller.rb
=> Render errors on plugin install

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/SYSTEM/procedures/interactive.rb, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/PromptDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue, openc3-cosmos-script-runner-api/app/controllers/running_script_controller.rb, openc3-cosmos-script-runner-api/app/models/running_script.rb, openc3-cosmos-script-runner-api/scripts/run_script.rb, openc3/lib/openc3/script/api_shared.rb, openc3/templates/target/targets/TARGET/lib/target.rb
=> Allow multiselect

openc3-cosmos-cmd-tlm-api/config/initializers/cts.rb, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/ClassificationBannerSettings.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/SettingsTab.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/AppFooter.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/components/ClassificationBanners.vue, openc3/data/config/_canvas_values.yaml, openc3/data/config/command.yaml, openc3/data/config/command_modifiers.yaml, openc3/data/config/graph_settings.yaml, openc3/data/config/interface_modifiers.yaml, openc3/data/config/item_modifiers.yaml, openc3/data/config/microservice.yaml, openc3/data/config/plugins.yaml, openc3/data/config/screen.yaml, openc3/data/config/target.yaml, openc3/data/config/telemetry.yaml, openc3/data/config/telemetry_modifiers.yaml, openc3/data/config/tool.yaml, openc3/data/config/widgets.yaml, openc3/lib/openc3/api/settings_api.rb, openc3/lib/openc3/models/scope_model.rb, openc3/lib/openc3/models/setting_model.rb, openc3/lib/openc3/models/tool_config_model.rb, openc3/lib/openc3/utilities/local_mode.rb, openc3/spec/utilities/local_mode_spec.rb
=> Save and load local tool config

.github/workflows/playwright.yml, openc3-cosmos-init/plugins/README.md, openc3.bat, openc3.sh, openc3/lib/openc3/io/raw_logger.rb, scripts/linux/openc3_setup.sh, scripts/linux/openc3_test.sh, scripts/windows/openc3_test.bat
=> Change docker-compose to docker compose

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/FileOpenSaveDialog.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/GraphEditItemDialog.vue
=> Allow user to graph limits

openc3/lib/openc3/api/cmd_api.rb
=> Fix get_cmd_value and get_cmd_time

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-packetviewer/src/tools/PacketViewer/PacketViewer.vue
=> Derived details

openc3/lib/openc3/io/json_api.rb, openc3/lib/openc3/script/web_socket_api.rb, openc3/lib/openc3/system/system.rb, openc3/spec/core_ext/io_spec.rb
This will allow requires like: require "TARGET/lib/my_file.rb" to work inside of microservices.
=> Add target folder to load path

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/services/openc3-api.js, openc3/lib/openc3/interfaces/interface.rb, openc3/lib/openc3/interfaces/stream_interface.rb
=> Fix connect_interface with params

openc3/lib/openc3/microservices/cleanup_microservice.rb
=> Cleanup logger as debug rather than info

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/plugin.txt, openc3/data/config/_interfaces.yaml, openc3/lib/openc3/interfaces/serial_interface.rb, openc3/lib/openc3/interfaces/tcpip_client_interface.rb, openc3/lib/openc3/interfaces/tcpip_server_interface.rb, openc3/lib/openc3/interfaces/udp_interface.rb, openc3/lib/openc3/io/serial_driver.rb, openc3/lib/openc3/streams/serial_stream.rb, openc3/lib/openc3/streams/tcpip_client_stream.rb, openc3/lib/openc3/streams/tcpip_socket_stream.rb, openc3/lib/openc3/streams/web_socket_client_stream.rb, openc3/spec/streams/serial_stream_spec.rb, openc3/spec/streams/tcpip_client_stream_spec.rb, openc3/spec/streams/tcpip_socket_stream_spec.rb
=> Force write_timeout to value and update docs

openc3/lib/openc3/api/cmd_api.rb, openc3/spec/api/cmd_api_spec.rb, openc3/spec/install/config/targets/INST/cmd_tlm/inst_cmds.txt
=> Add log_message parameter to cmd()

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-admin/package.json, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/PluginDialog.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PluginsTab.vue, openc3-cosmos-init/plugins/yarn.lock
=> Diff plugin.txt on upgrade

openc3-cosmos-cmd-tlm-api/app/controllers/gems_controller.rb, openc3-cosmos-cmd-tlm-api/app/controllers/plugins_controller.rb, openc3-cosmos-cmd-tlm-api/app/controllers/process_status_controller.rb, openc3-cosmos-cmd-tlm-api/config/routes.rb, openc3/bin/openc3cli, openc3/lib/openc3/models/gem_model.rb, openc3/lib/openc3/operators/operator.rb, openc3/lib/openc3/script/gems.rb, openc3/lib/openc3/script/plugins.rb, openc3/lib/openc3/script/script.rb, openc3/lib/openc3/utilities/process_manager.rb, openc3/spec/models/gem_model_spec.rb
=> Command line plugin and gem install/uninstall outside cluster

openc3/data/config/protocols.yaml, openc3/lib/openc3/interfaces/interface.rb, openc3/lib/openc3/interfaces/protocols/slip_protocol.rb, openc3/spec/interfaces/protocols/slip_protocol_spec.rb
=> Slip protocol

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/LabelvaluedescWidget.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/Widget.js
=> Do not set width if subsetting given

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
=> Show completed scripts when running script not found

openc3/data/config/protocols.yaml, openc3/lib/openc3/interfaces/protocols/cobs_protocol.rb, openc3/lib/openc3/interfaces/protocols/terminated_protocol.rb, openc3/spec/interfaces/protocols/cobs_protocol_spec.rb, openc3/spec/interfaces/protocols/slip_protocol_spec.rb
=> COBS Protocol

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/plugins/dialog/ConfirmDialog.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/plugins/dialog/index.js
=> dialog ok button styles

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/RawDialog.vue
=> Force raw dialog to top of window

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue, openc3/lib/openc3/utilities/authorization.rb, openc3/spec/logs/packet_log_writer_spec.rb
=> Configure frontend during script start

openc3-cosmos-init/plugins/openc3-tool-base/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-admin/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-autonomic/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-bucketexplorer/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-calendar/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/vue.config.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataextractor/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataviewer/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-handbooks/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-packetviewer/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tablemanager/src/router.js, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/router.js, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/NotFound.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/MicroservicesTab.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/AppNav.vue
=> Add not found component

openc3/lib/openc3/utilities/bucket_require.rb, openc3/lib/openc3/utilities/bucket_utilities.rb, openc3/spec/utilities/bucket_require_spec.rb
=> Better handle bucket require load failures

openc3-redis/redis.conf, openc3-redis/redis_ephemeral.conf
Enable redis IO threading to improve performance.
=> enable redis threading

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsMonitor.vue, playwright/tests/limits-monitor.spec.ts
=> Remove tabs in LimitsMonitor

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Openc3Screen.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/services/openc3-api.js
=> Better handle screen tlm request timeouts

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/ResultsDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/FileOpenSaveDialog.vue
=> Add spinner overlay to file load save dialog

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue, openc3/lib/openc3/utilities/local_mode.rb, openc3/spec/utilities/local_mode_spec.rb, scripts/linux/openc3_util.sh, scripts/windows/openc3_util.bat
=> Prevent loading previous script on script run

openc3/Rakefile, openc3/data/config/target.yaml, openc3/ext/openc3/ext/reducer_microservice/extconf.rb, openc3/ext/openc3/ext/reducer_microservice/reducer_microservice.c, openc3/lib/openc3/microservices/reducer_microservice.rb, openc3/lib/openc3/models/target_model.rb, openc3/lib/openc3/utilities/throttle.rb, openc3/openc3.gemspec
This is simply to break apart the big method for profiling. Both my flamegraphs determined update_min_stats() were taking the majority of the time.
=> Reducer improvements

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/services/cable.js, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/AppFooter.vue, openc3/templates/tool_svelte/.prettierrc.js, openc3/templates/tool_svelte/src/services/cable.js, openc3/templates/tool_svelte/src/services/openc3-api.js
=> encodeURI for action cable consumers

openc3-cosmos-init/plugins/packages/openc3-cosmos-ace-diff/src/index.js
=> Fix ace-diff alignment issues

openc3/lib/openc3/conversions/unix_time_conversion.rb
=> Allow using converted telemetry for UnixTimeConversion

openc3/python/openc3/io/json_rpc.py, openc3/python/test/io/test_json_rpc.py, openc3/python/test/script/test_api_shared.py, openc3/spec/io/json_rpc_spec.rb
=> Fix python encoding of binary

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/FileOpenSaveDialog.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/TopBar.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/util/fileIcon.js, playwright/tests/script-runner/file-menu.spec.ts
=> Add Open Recent to ScriptRunner, fix file icons

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/procedures/my_script_suite.py, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataextractor/src/tools/DataExtractor/DataExtractor.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataviewer/src/tools/DataViewer/DataViewer.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsMonitor.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-packetviewer/src/tools/PacketViewer/PacketViewer.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/TlmGrapher.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/TlmViewer.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/TargetPacketItemChooser.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/config/Config.js, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/config/OpenConfigDialog.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/config/SaveConfigDialog.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/SettingsTab.vue, playwright/tests/admin/settings.spec.ts, playwright/tests/data-extractor.spec.ts, playwright/tests/packet-viewer.spec.ts, playwright/utilities.ts
=> Default config

openc3/lib/openc3/packets/packet_config.rb, openc3/lib/openc3/packets/parsers/xtce_parser.rb, openc3/spec/packets/parsers/xtce_parser_spec.rb
Also Support .xtce or .xml extension
=> XTCE - Add ContainerRefEntry support - Ignore Ancillary 

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Openc3Screen.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/services/openc3-api.js, openc3/lib/openc3/api/limits_api.rb, openc3/lib/openc3/api/tlm_api.rb, openc3/lib/openc3/models/cvt_model.rb
=> Default to no tlm cache

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
=> Process ScriptRunner events in batches

openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb, openc3-cosmos-cmd-tlm-api/config/routes.rb
=> Fix bucket explorer route

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/TlmGrapher.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue
=> Fix Grapher load config

openc3/bin/openc3cli, openc3/lib/openc3/utilities/cli_generator.rb
=> Add requirements.txt to python gems

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/cmd_tlm/inst_cmds.txt, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/lib/sim_inst.rb, openc3/spec/packets/commands_spec.rb
=> Test command endianness

docs.openc3.com/docs/meta/licenses.md, openc3/lib/openc3/microservices/decom_microservice.rb, openc3/lib/openc3/microservices/log_microservice.rb, openc3/lib/openc3/microservices/microservice.rb, openc3/lib/openc3/models/microservice_model.rb, openc3/lib/openc3/models/plugin_model.rb, openc3/lib/openc3/models/target_model.rb, openc3/lib/openc3/operators/microservice_operator.rb, openc3/lib/openc3/packets/commands.rb, openc3/lib/openc3/packets/packet_config.rb, openc3/lib/openc3/packets/telemetry.rb, openc3/lib/openc3/system/system.rb, openc3/python/openc3/microservices/decom_microservice.py, openc3/python/openc3/microservices/microservice.py
Notifies Logging and Decom that new packets have been added and they need to listen to more topics.
Python support not fully implemented.  Will write another ticket for that.
=> Improve dynamic packet support

openc3/bin/openc3cli
=> Warn about rake without Rakefile

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/CmdPacketsTab.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/RawDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdtlmserver/src/tools/CmdTlmServer/TlmPacketsTab.vue, playwright/tests/cmd-tlm-server/cmd-pkts.spec.ts, playwright/tests/cmd-tlm-server/tlm-pkts.spec.ts
=> Allow multiple positionable raw dialogs

openc3-ruby/Dockerfile-ubi
=> Link pip3 to pip in ubi

openc3/bin/pipinstall, openc3/lib/openc3/models/plugin_model.rb
=> Pip install retry with no-index

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/assets/stylesheets/layout/_overrides.scss
=> Alternate list item colors

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/cmd_tlm/inst_cmds.txt, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/cmd_tlm/inst_tlm.txt, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/lib/sim_inst.rb, openc3/lib/openc3/api/cmd_api.rb, openc3/lib/openc3/api/tlm_api.rb, openc3/lib/openc3/models/target_model.rb, openc3/python/openc3/api/cmd_api.py, openc3/python/openc3/api/tlm_api.py, openc3/python/openc3/models/target_model.py, openc3/python/test/api/test_tlm_api.py, openc3/python/test/install/config/targets/INST/cmd_tlm/inst_tlm.txt, openc3/spec/api/tlm_api_spec.rb, openc3/spec/install/config/targets/INST/cmd_tlm/inst_tlm.txt, openc3/spec/models/target_model_spec.rb
=> Hide HIDDEN commands and packets

openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb, openc3-cosmos-cmd-tlm-api/config/routes.rb, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/ImageLoader.js, openc3/lib/openc3/utilities/aws_bucket.rb, openc3/lib/openc3/utilities/bucket.rb, openc3/python/openc3/utilities/aws_bucket.py, openc3/python/openc3/utilities/bucket.py, openc3/spec/utilities/aws_bucket_spec.rb
=> Download presigned requests check targets_modified

.env, INSTALL.md, docs.openc3.com/docs/development/developing.md
fixes openssl CVEs: https://www.alpinelinux.org/posts/Alpine-3.16.9-3.17.7-3.18.6-released.html
=> Bump alpine build

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/components/Notifications.vue, openc3-cosmos-script-runner-api/app/channels/all_scripts_channel.rb, openc3-cosmos-script-runner-api/app/models/running_script.rb, openc3-cosmos-script-runner-api/scripts/run_script.py, openc3-cosmos-script-runner-api/scripts/run_script.rb, openc3-cosmos-script-runner-api/scripts/running_script.py, openc3/lib/openc3/script/web_socket_api.rb, openc3/python/openc3/script/web_socket_api.py
My new AllScriptsChannel / all-scripts-channel isn't working yet. Not sure what I'm leaving out but I'm not getting any notifications.
closes #832
=> Add notifications for scripts

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/RunningScripts.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
=> Disconnect before connecting to running script

openc3.bat, openc3.sh
=> Better cli descriptions

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue
=> Better check for scientific notation

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/EditScreenDialog.vue
=> Download screen as lowercase screen name

docs.openc3.com/docs/development/curl.md
closes https://github.com/OpenC3/cosmos/issues/1139
=> Add Suite Runner Example to curl.md

openc3/lib/openc3/microservices/decom_microservice.rb, openc3/python/openc3/microservices/decom_microservice.py, openc3/python/test/api/test_limits_api.py, openc3/spec/api/limits_api_spec.rb
=> Suppress initial limits INFO msgs

openc3/python/openc3/script/commands.py
=> Fix sending array in python

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/TargetPacketItemChooser.vue, openc3/lib/openc3/packets/structure.rb, playwright/tests/global.setup.ts
=> Fix accessor for Python

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue, playwright/tests/limits-monitor.spec.ts
=> Add Clear All to ignored limits

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue, playwright/tests/command-sender.spec.ts
=> Command Sender remember history

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/autocomplete/packetCompleter.js
=> Allow fstring in code completion

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-packetviewer/src/tools/PacketViewer/PacketViewer.vue
=> Do not clear interval on Packet Viewer error

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/components/Notifications.vue
=> Notifications: Only open if url, change clear icon

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/ModifiedPluginDialog.vue
=> Change modified button to Confirm

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue
=> Limits Monitor timestamp and more width

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataviewer/src/tools/DataViewer/DataViewer.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/dataviewer/HistoryComponent.vue
=> DataViewer collapsable header and full height

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptLogMessages.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue, openc3/lib/openc3/models/target_model.rb
=> Script Runner panes

openc3-cosmos-cmd-tlm-api/app/controllers/scopes_controller.rb, openc3/lib/openc3/models/target_model.rb, openc3/lib/openc3/packets/packet.rb
=> Deploy new scopes

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataviewer/src/tools/DataViewer/AddComponentDialog.vue
=> Allow cmds in Data Viewer

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PluginsTab.vue, openc3-cosmos-script-runner-api/scripts/script_instrumentor.py, openc3/lib/openc3/models/activity_model.rb, openc3/lib/openc3/script/calendar.rb, openc3/python/openc3/script/cosmos_calendar.py, openc3/python/requirements-dev.txt, openc3/spec/models/activity_model_spec.rb
=> Fix python break and plugin download and calendar reserve type

openc3-cosmos-init/plugins/openc3-tool-base/src/App.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/AppFooter.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/base/AppNav.vue
Just add ?chromeless=1 to the url and all the chrome is gone!
=> Add chromeless query parameter support

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/procedures/file_dialog.py, openc3-cosmos-script-runner-api/scripts/running_script.py
=> Fix python open_file_dialog

openc3/lib/openc3/accessors/template_accessor.rb, openc3/spec/accessors/template_accessor_spec.rb
=> Better escaping in TemplateAccessor

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue, openc3/lib/openc3/models/activity_model.rb, playwright/tests/command-sender.spec.ts
=> Fix Command Sender error message

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/SpacerWidget.vue
=> Fix spacer widget

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/FileOpenSaveDialog.vue
=> Update SR file open / save dialog

openc3-cosmos-cmd-tlm-api/config/initializers/cts.rb, openc3/lib/openc3/io/json_rpc.rb, openc3/lib/openc3/utilities/target_file.rb
closes https://github.com/OpenC3/cosmos-enterprise/issues/162
=> Improve target file performance

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/TlmGrapher.vue, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/Graph.vue
=> Add ability to clear graph data

openc3/lib/openc3/models/cvt_model.rb, openc3/python/openc3/models/cvt_model.py, playwright/tests/bucket-explorer.spec.ts, playwright/tests/data-extractor.spec.ts, playwright/tests/script-runner/api.spec.ts
=> RECEIVED_COUNT returns 0 if packet not received

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/lib/example_limits_response.rb, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/procedures/checks.rb, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/lib/example_limits_response.py, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/procedures/checks.py, openc3/lib/openc3/api/cmd_api.rb, openc3/lib/openc3/microservices/interface_microservice.rb, openc3/lib/openc3/script/commands.rb, openc3/python/openc3/api/cmd_api.py, openc3/python/openc3/microservices/interface_microservice.py, openc3/python/openc3/script/commands.py
The validator is the thing you set but the command reads better as validate true / false I think. This also adds the keyword to the script api.
=> Change cmd keyword from validator to validate

RELEASE.txt, openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/VWidget.js, openc3-cosmos-script-runner-api/scripts/running_script.py
closes https://github.com/OpenC3/cosmos-enterprise/issues/165
=> Fix python sleep and screen formatValue

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-bucketexplorer/src/tools/BucketExplorer/BucketExplorer.vue, playwright/tests/bucket-explorer.spec.ts
=> Add auto-refresh to Bucket Explorer

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/procedures/my_test_suite.rb, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/procedures/my_test_suite.py, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/SuiteRunner.vue, openc3/python/test/interfaces/test_interface.py, playwright/tests/script-runner/suite.spec.ts
=> Strip script_ and test_ from suite names

openc3/lib/openc3/microservices/timeline_microservice.rb, openc3/lib/openc3/models/activity_model.rb, openc3/spec/microservices/timeline_microservice_spec.rb
closes https://github.com/OpenC3/cosmos-enterprise/issues/178
=> Fix timeline to handle events at same time

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/LinegraphWidget.vue
=> Add time zone to LinegraphWidget

openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/LedWidget.vue
=> Add LedWidget hover

openc3-cosmos-init/plugins/openc3-tool-base/src/App.vue
=> Allow horizontal scrolling in apps

examples/hostinstall/centos7/traefik.yaml, openc3-traefik/Dockerfile, openc3-traefik/traefik-allow-http.yaml, openc3-traefik/traefik-dev-base.yaml, openc3-traefik/traefik-dev.yaml, openc3-traefik/traefik-letsencrypt.yaml, openc3-traefik/traefik-ssl.yaml, openc3-traefik/traefik.yaml
=> Traefik v3 (COSMOS 6)

openc3/python/openc3/accessors/template_accessor.py, openc3/python/openc3/script/suite_runner.py, openc3/python/test/api/test_tlm_api.py
=> Fix Python Suite Setup and Teardown

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptLogMessages.vue
=> Better handle script output coloring

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/TlmGrapher.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue
=> Fix graph layout

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/PackagesTab.vue, openc3/bin/pipinstall, openc3/bin/pipuninstall, openc3/lib/openc3/models/python_package_model.rb
=> Fix pip uninstall, improve package status

docs.openc3.com/docs/development/developing.md, openc3.code-workspace
=> Dev doc updates

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/VWidget.js
Closes https://github.com/OpenC3/cosmos/issues/1922
=> Fix case sensitivity for timestamp formatting

.github/workflows/release.yml
=> Add yarn build to release

.github/workflows/release.yml, scripts/release/build_multi_arch.sh
I need to push the base containers to build the Enterprise containers
=> Build UBI images as part of the release

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue, playwright/tests/limits-monitor.spec.ts
closes #1839
closes #1840
closes #1841
=> Limits Monitor Data Table, Sorting, Search, and Menu

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/HorizontalboxWidget.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/VerticalboxWidget.vue
=> Fix Graph without overview

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/TreeNode.vue
Still not sure how this ever worked before or why it suddenly broke for me but I think this is the fix to the treenode errors. Let me know if you think I covered it and what is going on here.
=> Fix treenode value

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/SettingsDialog.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/TlmGrapher.vue, openc3-cosmos-init/plugins/packages/openc3-tool-base/src/assets/stylesheets/layout/_overrides.scss, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue
closes https://github.com/OpenC3/cosmos/issues/2017
Bugs fixed:
- selected range highlight color (#2017)
- ~graph widths overflowing page~ still broken - will fix later
- selected graph toolbar color not updating
Feature add:
- new "Add Graph" button when there are no graphs (just to save a click - this bothered me lol)
=> TlmGrapher improvements

openc3/python/openc3/io/udp_sockets.py, openc3/python/test/io/test_udp_sockets.py
=> Python UDP sockets handle disconnect / reconnect

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue
I just reverted it back to what it was before my last change and that fixed it?
This needs to be redone completely, but will punt on that as per discussion in standup
=> Fix graph widths

openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/screens/hs.txt, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/screens/hs.txt, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/EditScreenDialog.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Openc3Screen.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/ace/AceEditorUtils.js, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/EditDialog.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/PluginDialog.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/base/AppFooter.vue
=> Allow settings to override global settings

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Openc3Screen.vue
=> update overlay behaviour

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/RunningScripts.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue, openc3-cosmos-script-runner-api/app/models/running_script.rb, openc3-cosmos-script-runner-api/scripts/run_script.py, openc3-cosmos-script-runner-api/scripts/run_script.rb, openc3-cosmos-script-runner-api/scripts/running_script.py, openc3/lib/openc3/models/script_status_model.rb, openc3/python/openc3/models/script_status_model.py, playwright/tests/script-runner/api.s.spec.ts, playwright/tests/script-runner/script-menu.p.spec.ts
=> Fix script connect error if completed

docs.openc3.com/docs/getting-started/upgrading.md
I'll regen site before merging but waiting on the other PR to close
=> Detail upgrade migration steps

openc3-cosmos-cmd-tlm-api/app/controllers/internal_metrics_controller.rb, openc3-cosmos-cmd-tlm-api/spec/controllers/activity_controller_spec.rb, openc3-cosmos-cmd-tlm-api/spec/controllers/internal_metrics_controller_spec.rb, openc3-cosmos-cmd-tlm-api/spec/controllers/plugins_controller_spec.rb, openc3-cosmos-cmd-tlm-api/spec/models/message_file_reader_spec.rb, openc3-cosmos-cmd-tlm-api/spec/models/messages_api_spec.rb, openc3-cosmos-cmd-tlm-api/spec/models/messages_thread_spec.rb, openc3-cosmos-cmd-tlm-api/spec/models/topics_thread_spec.rb
- Updated unit tests in cmd/tlm api to achieve >80% coverage
- Minor update to internal_metrics_controller to prevent multiple-render
- Some formatter noise (Standard Ruby)
=> [Unit Tests] - Cmd/Tlm API (Primarily Models)

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Openc3Screen.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/VWidget.js
Currently this does nothing:
FORMATVALUE INST HEALTH_STATUS PACKET_TIMEFORMATTED %.19s RAW 22
This change allow formatting to our TIMEFORMATTED values
=> Allow formatting on TIMEFORMATTED values

openc3/python/openc3/packets/commands.py, openc3/python/openc3/packets/structure.py, openc3/python/test/packets/test_packet.py, openc3/spec/packets/packet_spec.rb
=> Fix python fixed size calculation

docs.openc3.com/docs/guides/scripting-api.md
Partially addresses #2106
Will be fully addressed when Command Sender implements command validation.
=> Document Command Validation

openc3/lib/openc3/packets/structure.rb, openc3/python/openc3/accessors/binary_accessor.py, openc3/python/openc3/packets/structure.py, openc3/python/test/accessors/test_binary_accessor_write.py, openc3/spec/accessors/binary_accessor_spec.rb
=> Fix variable bit size array items

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Openc3Screen.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/HorizontalWidget.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/HorizontalboxWidget.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/MatrixbycolumnsWidget.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/ScrollwindowWidget.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/VerticalWidget.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/VerticalboxWidget.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/Widget.js
=> Differentiate RAW widget settings

openc3/lib/openc3/models/tool_model.rb, openc3/spec/models/tool_model_spec.rb
=> Allow well formed URLs

docs.openc3.com/docs/guides/scripting-api.md
=> Fix scripting-api documentation

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/GraphEditDialog.vue
- Fixed prose around custom x-axis items
- Fixed issue when graphing an item against itself (both axes)
- Some code cleanup in Graph.vue
=> Custom x-axis item fixes

docs.openc3.com/docs/configuration/protocols.md
=> Update docs for CRC protocol default settings

openc3/lib/openc3/microservices/interface_microservice.rb, openc3/python/openc3/microservices/interface_microservice.py
Test via:
```
puts get_interface("EXAMPLE_INT")
connect_interface("EXAMPLE_INT", "host", 12345)
puts get_interface("EXAMPLE_INT")
puts get_interface("INST2_INT")
connect_interface("INST2_INT", "helper.py")
puts get_interface("INST2_INT")
```
=> Update InterfaceModel when changing params

openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-dataviewer/src/tools/DataViewer/DataViewer.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmgrapher/src/tools/TlmGrapher/TlmGrapher.vue, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-tlmviewer/src/tools/TlmViewer/TlmViewer.vue, openc3-cosmos-init/plugins/packages/openc3-tool-base/src/assets/stylesheets/layout/_overrides.scss, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/dataviewer/DataViewerHistoryComponent.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/plugins/plugin-store/PluginDetailsDialog.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/plugins/plugin-store/PluginProps.js, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/PluginsTab.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/plugins/PluginList.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/plugins/PluginListItem.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/plugins/index.js
- Fix mdi-chevrons that were pulsing when they weren't supposed to
- Pull the plugin list into its own component to get ready for more changes
=> Misc cleanup

openc3.sh
Let me know what you all think about the messaging that this gives. Once approved, I'll make the same changes to cosmos-project, cosmos-enterprise, and cosmos-enterprise-project
closes #2288
=> Add messaging if sudo is used when deploying COSMOS

openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue, openc3/lib/openc3/api/tlm_api.rb, openc3/python/openc3/microservices/quest_microservice.py
=> Convert db column to correct type

openc3-cosmos-cmd-tlm-api/app/controllers/queues_controller.rb, openc3-cosmos-cmd-tlm-api/spec/controllers/queues_controller_spec.rb, openc3/bin/openc3cli
=> [Bug] Queues

openc3-cosmos-cmd-tlm-api/app/controllers/application_controller.rb, openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/ace/AceEditorUtils.js, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/admin/tabs/settings/EditorSettings.vue, openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue, playwright/tests/admin/settings.p.spec.ts, playwright/tests/script-runner/api.s.spec.ts, playwright/tests/script-runner/debug.s.spec.ts, playwright/tests/script-runner/prompts.p.spec.ts, playwright/tests/script-runner/script-menu.p.spec.ts, playwright/tests/script-runner/suite.s.spec.ts, playwright/tests/tlm-viewer.p.spec.ts
=> Script default language setting

docs.openc3.com/docs/getting-started/installation.md
=> Add the getting started video to the docs

docs.openc3.com/docs/guides/scripting-api.md, openc3-cosmos-cmd-tlm-api/app/controllers/queues_controller.rb, openc3-cosmos-cmd-tlm-api/spec/controllers/queues_controller_spec.rb, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/procedures/queue.rb, openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/procedures/queue.py, openc3-cosmos-init/plugins/packages/openc3-tool-base/src/assets/stylesheets/layout/_overrides.scss, openc3/lib/openc3/microservices/queue_microservice.rb, openc3/lib/openc3/models/microservice_model.rb, openc3/lib/openc3/models/queue_model.rb, openc3/lib/openc3/script/queue.rb, openc3/python/openc3/script/queue.py, openc3/spec/microservices/queue_microservice_spec.rb, openc3/spec/models/queue_model_spec.rb, openc3/spec/models/script_status_model_spec.rb
closes https://github.com/OpenC3/cosmos-enterprise/issues/312
closes https://github.com/OpenC3/cosmos-enterprise/issues/313
=> Add queue_remove to scripting API
